### ISSUE TITLE
Support default manifest without explicit parameter

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-wskdeploy#1020]
Small UX feedback... Could we support using a default manifest (`manifest.yml `) from the current directory if the user doesn't explicitly provide one as a command-line argument? 

This would allow me to just type `wskdeploy` rather than `wskdeploy -m manifest.yml` all the time.

**Comment by pritidesai** [comment]
@jthomas this is supported, `wskdeploy` looks for `manifest.yaml` first followed by `manifest.yml` in current directory at https://github.com/apache/incubator-openwhisk-wskdeploy/blob/7bf2617461857e77642b3f82e99ffa1d9691d783/utils/misc.go#L108
