### ISSUE TITLE
Api paths are getting created under the wrong api with manifest.yaml

### ISSUE THREAD

**Issue by playground** [apache/incubator-openwhisk-wskdeploy#1028]
manifest.yaml
```
packages:
  ibmcos:
    version: 1.0
    license: Apache-2.0
    actions:
      cos-dashboard-action:
        function: dist/cos-dashboard-action.js
        runtime: nodejs:8
        web-export: true
        inputs:
          bucket: ${BUCKET}
          accessKeyId: ${ACCESSKEYID}
          secretAccessKey: ${SECRETACCESSKEY}
    apis:
      cos-dashboard:
        api:
          list:
            cos-dashboard-action:
              method: GET
              response: http
          upload:
            cos-dashboard-action:
              method: POST
              response: http
```
```
deploying...
Info: The API host is [us-south.functions.cloud.ibm.com], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [_], from .wskprops.
Info: The apigw access token is set, from .wskprops.
Info: Unmarshal OpenWhisk runtimes from internet at https://us-south.functions.cloud.ibm.com.
Info: Deploying package [ibmcos] ...
Info: package [ibmcos] has been successfully deployed.

Info: Deploying action [ibmcos/cos-dashboard-action] ...
Info: action [ibmcos/cos-dashboard-action] has been successfully deployed.

Info: Deploying api [cos-dashboard /api/list GET] ...
Info: api [cos-dashboard /api/list GET] has been successfully deployed.

Info: Deploying api [cos-dashboard /api/upload POST] ...
Info: api [cos-dashboard /api/upload POST] has been successfully deployed.

Success: Deployment completed successfully.
```
According to the deploy log, both api/list and api/upload should have been created under api named "cos-dashboard".  However they are being created under "starter-apis"
![image](https://user-images.githubusercontent.com/243495/52168341-1f92c200-26f7-11e9-899a-bfd2c11e8cf6.png)

**Comment by csantanapr** [comment]
Thanks for reporting the issue @playground 

@mdeuser ^^

**Comment by csantanapr** [comment]
It would be helpful if you could open a ticket with IBM Cloud on this to have support jump to also help.

**Comment by playground** [comment]
@mdeuser yes I already have starter-apis defined as a test which as a base path of /api.  So I can't have a base path with the name /api even though it is for a new endpoint name?

**Comment by mdeuser** [comment]
@playground - you can add new endpoints to an existing api.  the new endpoints would specify the existing basepath, which in your case is `/api`.  however, the new endpoints are not able to rename the api. in your case the existing api (base path `/api`, name `starter-apsi`) will retain the name `starter-apis` even though the new endpoints try to specify a different api name (`cos-dashboard`).  an api can only have one api name and one basepath.  if you really want another api with the name `cos-dashboard` just use a new basepath.
