### ISSUE TITLE
[WIP] Add verify command.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#107]
Add a verify command which would read the manifest and deployment files, then check to see what is already installed in OpenWhisk. 
This is a derivative of https://github.com/openwhisk/openwhisk-wskdeploy/issues/93

**Comment by paulcastro** [comment]
Sounds good - we can do this in two phases.  The undeploy function can take arrays of entities (from the manifest) that should be undeployed.  In the first phase, we just pass all the entities from the manifest even if they aren't deployed.  In the second phase, we add the verification step which takes the entities from the manifest, and filters out the entities that haven't been deployed and then passes them to the undeploy function(s). 

I can create the undeploy functions if you are already working on verification.

**Comment by paulcastro** [comment]
I made a PR for undeploy #110

**Comment by lzbj** [comment]
Ok, thanks, hope I got a chance to submit a pr regarding this issue. :-)

**Comment by lzbj** [comment]
Close is as I think it's not necessary feature and  on the critical path any more.
