### ISSUE TITLE
whiskbot test case failure.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#114]
When I run the whiskbot test cases, I got a failure "2017/02/17 13:41:42 error happened during unmarshal :yaml: line 43: did not find expected key", need to investigate and fix this one.

**Comment by lzbj** [comment]
It seems test datas included in this test cases are not supported yet, right? @paulcastro

**Comment by paulcastro** [comment]
Yes, correct.   Still need to add support for some keys like api-experimental

**Comment by mrutkows** [comment]
@lzbj Please contact Paul and see if this is still a valid use case?  If not, close... If it is still valid we should fix it.

**Comment by pritidesai** [comment]
Paul got back saying `whiskbot` was created to test the `dependencies` key, couldn't get more info form him.

**Comment by mrutkows** [comment]
@priti Will close this for now; can we work to remove this from use cases directory.
