### ISSUE TITLE
typo seqeunces in whiskbot manifest

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-wskdeploy#118]
seqeunces: in https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/tests/testcases/whiskbot/manifest.yaml#L44

**Comment by mrutkows** [comment]
Priti indicated whiskbot is now under tests/usecases.

**Comment by daisy-ycguo** [comment]
I verified. There is no typo error "seqeunces" in manifest.yaml. So I will close this issue.
