### ISSUE TITLE
Potential runtime name inconsistency

### ISSUE THREAD

**Issue by lionelvillard** [apache/incubator-openwhisk-wskdeploy#121]
wsk specify the runtime version after `:`, like this:

    wsk action create packageAction --kind nodejs:6 action.zip

The package specification uses `@`, i.e `nodejs@6`

So the question is: should both names be the same?

**Comment by paulcastro** [comment]
Yes.

**Comment by paulcastro** [comment]
Our current implementation will throw an error if you don't use the kinds specified by OW.  We should update the spec.

**Comment by lzbj** [comment]
fixed.
