### ISSUE TITLE
Implement namespace swap command

### ISSUE THREAD

**Issue by paulcastro** [apache/incubator-openwhisk-wskdeploy#122]
wskdeploy commands run in the context of a single OW namespace. This means a deployment will utilize only that namespace.  Managing multiple versions of deployments over several namespaces could be important because it allows a developer to have a "production" version of a deployment and several test versions.  To make managing this easier, we could add a `swap` command, which would allow a develop to swap the namespaces of two different versions of a deployment using a single command.

**Comment by pritidesai** [comment]
We have a way to specify which `namespace` should have all the entities deployed on command line using `--namespace`. Also, namespace is read in the following precedence order:

(1) wskdeploy command line `wskdeploy --apihost --namespace --auth`
(2) deployment file
(3) manifest file
(4) .wskprops

Closing this issue as this feature is supported in Whisk Deploy.
