### ISSUE TITLE
Considering removing development branch

### ISSUE THREAD

**Issue by lionelvillard** [apache/incubator-openwhisk-wskdeploy#125]
It is common practice to use the master branch for day-to-day development and use branches for releases/features. A good article on this topic can be found here: https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/

Should we delete the development branch (after merging it to master)?

**Comment by paulcastro** [comment]
I support this.

**Comment by csantanapr** [comment]
Yes I agree "master" for dev
As long master is always green gated by Travis CI

Other branches when ever we need a branch release

**Comment by mrutkows** [comment]
development branch was deleted several months ago.
