### ISSUE TITLE
Update use case: data-processing-app

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#182]
The use case is copied from [openwhisk-data-processing-messagehub](https://github.com/IBM/openwhisk-data-processing-message-hub). Now we are able to support env variables. We should update this use case to show the capability.

**Comment by daisy-ycguo** [comment]
Just run this case, it gets an error while installing:
```
Deploying pacakge kafka ... Done!
Deploying action kafka/mhpost-action ... Done!
Deploying action kafka/mhget-action ... Done!
Deploying trigger kafka-trigger ... Done!
Deploying rule kafka-inbound-rule ... Got error creating rule with error message: {{.msg}} (code {{.code}}) and error code: 144.
Done!
```

We need to fix it.

**Comment by paulcastro** [comment]
@daisy-ycguo have you updated to the latest master in openwhisk-client-go?  If you do, you'll get the full error message instead of `{{.msg}}`.

**Comment by mrutkows** [comment]
@daisy-ycguo any update?

**Comment by daisy-ycguo** [comment]
Duplicated with 352. Close it.
