### ISSUE TITLE
Support full command line switches/flags for manifest (or any file) argument

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#202]
Would suggest changing -m to --manifest or adding it as a full alternative (short single letter switches are usually reserved for toggle functions, filenames usually are part of the syntax or spelled out for files).  You can support both, but any 'file" argument should have a full switch "--name".

**Comment by mrutkows** [comment]
Help needs to document this behavior. Paul indicates the Go lib. we use supports short and long flags, but perhaps we do not show in our help output.  Please verify.

**Comment by lzbj** [comment]
fixed.
