### ISSUE TITLE
Add more CI test cases.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#203]
Now as we started the job of support CI with Openwhisk deployments, we still lack util codes to support CI test, we need to add this infra/shim.

**Comment by mrutkows** [comment]
Need more details @lzbj ... is there another related issue to this?

**Comment by lzbj** [comment]
@mrutkows , yes, I'll work with Vincent about the CI, I think he already resolved part of this issue, I'll close this one once we finished at least one CI test.

**Comment by lzbj** [comment]
@mrutkows @houshengbo , I updated the title since we have infra available now, we need to add more CI test cases.

**Comment by houshengbo** [comment]
@lzbj @mrutkows I have already set up the Travis CI and the first integration test https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/tests/src/integration/triggerrule/triggerrule_test.go, which runs automatically in Travis CI.

**Comment by lzbj** [comment]
@mrutkows @houshengbo , tks for your great job, I appreciate it. Yes, I'll modify submitted PR reference your test codes.

**Comment by lzbj** [comment]
I think we have enough CI test cases now despite we'll add more.
