### ISSUE TITLE
Add a timeout to access the baseurl

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#206]
If the baseurl we are about to access is not valid, it will take a very long time to get the error response. Suggest to add a timeout for whiskclient to access the baseurl.

**Comment by lzbj** [comment]
@houshengbo , are you still look at this issue, could you give a little more info in the issue description, so I can fix it if you not available?

**Comment by houshengbo** [comment]
#481 fixed this bug.
