### ISSUE TITLE
Can't update specification document

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-wskdeploy#217]
Specification document is only available as pdf https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/specification/openwhisk_v0.8.pdf

I was trying to update the spec to fix #216 but the original word document is not available in the repository.

Please add the word document in the repository to allow other folks be able to update the spec.

**Comment by jthomas** [comment]
Could we have a Markdown copy to make it easy to raise issues and submit PRs against?

**Comment by csantanapr** [comment]
Would be ideal to have it markdown or at least a google doc if it requires more complex formatting than what markdown can support

**Comment by lzbj** [comment]
Also helpful if the spec could come up with a catalog

**Comment by mrutkows** [comment]
The long term goal was to have the PDF be canonical (still true) and provide a non-canonical version as markdown (and use a converter like pandoc), but conversion is not perfect.  Will look into this again. @csantanapr  In general, conversion fails with tables... as each markdown impl. does this slightly differently, https://guides.github.com/features/mastering-markdown/

**Comment by csantanapr** [comment]
I do tables in excel having a "|" columns to separate, then I export to text giving me a compatible markdown github table.

**Comment by mrutkows** [comment]
@csantanapr @jthomas added markdown/HTML (non-normative) pages for most sections of the specification via PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/551

Both the spec. and evolving prog. guide are linked form the wskdeploy project README
