### ISSUE TITLE
Tests for wskdeploy binaries

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#241]
There is a similar discussion for the openwhisk CLI repo as well. Currently Travis CI is able to release the binaries automatically, but there is no tests running on top of the generated binaries. There is still risk that we generate binaries with errors.

An approach is to change our integration tests by calling the command directly based on the binaries we generate in Travis, which supports mac and Linux so far. For windows binary, we can enable AppVeyor in our repo to do the build for us. We need project admins to enable AppVeyor for openwhisk-wskdeploy, if we decide to use AppVeyor to do windows build. @mrutkows @paulcastro

**Comment by mrutkows** [comment]
AppVeyor should now be an approved 3rd party integration for all OpenWhisk repos.
<img width="1174" alt="screen shot 2017-04-18 at 3 02 23 pm" src="https://cloud.githubusercontent.com/assets/7816715/25182256/a55d0354-24d9-11e7-85c1-5a19fbb6c024.png">

**Comment by mrutkows** [comment]
The current Go impl. supports cross-compiled binary for all OS and ARCH.
