### ISSUE TITLE
zip action use case and test

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#245]
@lzbj used to submit a patch: https://github.com/openwhisk/openwhisk-wskdeploy/commit/e7b641d2924e45018b572e17d5f65d1cf1dcf879 adding the folder zip.

Is this the zip action we mentioned? @mrutkows @krook 

We are missing the use case for it.

**Comment by lzbj** [comment]
yes, I'll add a test for it.

**Comment by krook** [comment]
@houshengbo Yes, this would be for zipped actions.
