### ISSUE TITLE
Possible API gate regression due to openwhisk-client-go changes

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#255]
There have been quite some changes in openwhisk-client-go. After we pin to the latest commit number of openwhisk-client-go, a lot of method calls have to be changed accordingly.

However, there is probably a API gateway regression in wskdeploy, since in the CreateAPI method of api.go,
_, _, err := deployer.Client.Apis.Insert(api, true) was changed to
_, _, err := deployer.Client.Apis.Insert(api, nil, true), in order to make sure the binary build passes.

We have to verify if the api gateway still works in wskdeploy and adding an integration would be a great option.

@lzbj Could you take a look? Thx. Please update your openwhisk-client-go to the latest.

**Comment by csantanapr** [comment]
@houshengbo take into account that there is a new api gateway implementation `wsk api`, the old `wsk api-experimental` would be sunset.

**Comment by lzbj** [comment]
@houshengbo , so I'll add test code as you already submitted the fix right? sorry for late reply we were on labor's holiday, and the office resumed today.

**Comment by mrutkows** [comment]
@lzbj is there any status on this?

**Comment by lzbj** [comment]
@mrutkows , I'll add test code for the api use case. As @csantanapr  said, currently the experimental api may sunset, we may also update the code as the latest implementation.

**Comment by lzbj** [comment]
as the code that can build now, I would lower the pri to mid, please rise if not agree.

**Comment by lzbj** [comment]
@mrutkows , when I try to fix this issue, I found there were 2  grammar in our spec, one is simple format, one is full grammar, but as our yaml parsers are predefined structures which is a reflection of our grammar structure, so I don't which grammar to support? could you help clarify this issue?

**Comment by mrutkows** [comment]
@lzbj we decided (together) to use the full grammar (for first pass) and open a new issue to subsequently support the simple grammar later.

**Comment by mrutkows** [comment]
The signature of the Insert() method is now correct in current build within ServiceDeployer.go
