### ISSUE TITLE
Mac build problems

### ISSUE THREAD

**Issue by krook** [apache/incubator-openwhisk-wskdeploy#257]
I'm new to Go, but I wanted to build the latest binary (which isn't yet released) on my Mac workstation off of master (is the develop branch still the one I should build from per the README? Seems like a later version is in master now).

I was originally using go 1.2.1 and 1.2.2 installed from Homebrew on macOS El Capitan 10.11.6 some time ago and saw these errors when trying to build off the README instructions:

```bash
Genet:go krook$ go get github.com/openwhisk/openwhisk-wskdeploy
# golang.org/x/sys/unix
src/golang.org/x/sys/unix/syscall_solaris.go:27: SockaddrDatalink redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_darwin.go:39
src/golang.org/x/sys/unix/syscall_solaris.go:47: direntIno redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_darwin.go:79
src/golang.org/x/sys/unix/syscall_solaris.go:51: direntReclen redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_darwin.go:83
src/golang.org/x/sys/unix/syscall_solaris.go:55: direntNamlen redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_darwin.go:87
src/golang.org/x/sys/unix/syscall_solaris.go:65: Pipe redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_darwin.go:167
src/golang.org/x/sys/unix/syscall_solaris.go:79: (*SockaddrInet4).sockaddr redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_bsd.go:147
src/golang.org/x/sys/unix/syscall_solaris.go:93: (*SockaddrInet6).sockaddr redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_bsd.go:162
src/golang.org/x/sys/unix/syscall_solaris.go:108: (*SockaddrUnix).sockaddr redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_bsd.go:178
src/golang.org/x/sys/unix/syscall_solaris.go:134: Getsockname redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_bsd.go:297
src/golang.org/x/sys/unix/syscall_solaris.go:143: ImplementsGetwd redeclared in this block
    previous declaration at src/golang.org/x/sys/unix/syscall_darwin.go:21
src/golang.org/x/sys/unix/syscall_solaris.go:143: too many errors
# github.com/openwhisk/openwhisk-client-go/whisk
src/github.com/openwhisk/openwhisk-client-go/whisk/client.go:165: encoder.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)
src/github.com/openwhisk/openwhisk-client-go/whisk/client.go:542: encoder.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)
```

Based on some Googling, I then removed that Homebrew version and installed the latest 1.8.1 package from golang.org, but started to see this issue instead, which blocks me from building.

```bash
Genet:go krook$ go get github.com/openwhisk/openwhisk-wskdeploy
# github.com/spf13/viper
src/github.com/spf13/viper/flags.go:3: import /Users/krook/go/pkg/darwin_amd64/github.com/spf13/pflag.a: not a package file
# github.com/openwhisk/openwhisk-client-go/whisk
src/github.com/openwhisk/openwhisk-client-go/whisk/action.go:25: import /Users/krook/go/pkg/darwin_amd64/github.com/openwhisk/openwhisk-client-go/wski18n.a: not a package file
```

 Any tips?

**Comment by krook** [comment]
I was able to install wskdeploy using the Gradle and Docker approach, so this isn't critical to me. However, it should be looked into. Perhaps a list of environment prereq's for Mac?

**Comment by houshengbo** [comment]
Hi Dan,

When you download the latest source code of openwhisk-wskdeploy, open a
terminal and go to this openwhisk-wskdeploy folder.

You can build the binary either by running "make build" or go build -o
wskdeploy.

Normally, the make build command should work, since the it has taken the
installation of dependencies in to account.
If "go build -o wskdeploy" does not work, you can run "go get -d -t ./..."
to install all the dependencies, which is missing in the README.

If you have any questions regarding the binary build, feel free to contact
me.

Best wishes.
Vincent Hou (侯胜博)

Advisory Software Engineer, OpenStack Contributor, IaaS and OpenStack
Department, Open Technology, IBM Cloud

Notes ID: Vincent S Hou/Raleigh/IBM, E-mail: shou@us.ibm.com,
Phone: +1(919)254-7182
Address: 4205 S Miami Blvd (Cornwallis Drive), Durham, NC 27703, United
States

**Comment by krook** [comment]
Thanks for the reply @houshengbo. I did get it working with the Gradle build approach, and I see that you released a new binary, so I think I have what I need for the time being. I may come back to test the solution you suggested at a later time if I needed an updated build.

**Comment by mrutkows** [comment]
@krook Daniel, have not heard any update on this so am going to close for now.  Do not want you to have to use gradle, but use Go with makefile.  If you can try again, and open another issue to work through if needed that would be great.  We have several people able to build with Go (both ways) and assume it is some dependency or conflict locally?
