### ISSUE TITLE
Update package imports to "apache" (github) relative

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#263]
As we have moved to Apache org. under Github,  we should change package import statements to reflect this change...

for example:
import (
	"github.com/openwhisk/openwhisk-client-go/whisk"
        "github.com/openwhisk/openwhisk-wskdeploy/config"
}

should be:
import (
	"github.com/apache/incubator-openwhisk-client-go/whisk"
        "github.com/apache/incubator-openwhisk-wskdeploy/config"
}

**Comment by lzbj** [comment]
close as merged
