### ISSUE TITLE
Bump go to 1.8 and gradle to 3.5 as openwhisk core repo.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#270]
We'd better bump golang to 1.8 and gradle to 3.5 as core repo, which could reduce build time and size.

**Comment by daisy-ycguo** [comment]
openwhisk-cli and openwhisk-go-client still use golang 1.7. 
wskdeploy depends on openwhisk-cli, and I think these two projects will integrate in the future.
Do we really need to bump to 1.8?

**Comment by mrutkows** [comment]
@houshengbo @csantanapr Comments Vincent from the CLI perspective?

**Comment by lzbj** [comment]
maybe openwhisk-cli and openwhisk-go-client needs bump? I reviewed core repo, they use gradle 3.5 and go 1.8.

**Comment by mrutkows** [comment]
See PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/271
