### ISSUE TITLE
Remove unused/commented code in mhget.js

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#282]
/tests/usecases/data-processing-app/actions/mhget/mhget.js

has commented out code; if it is not needed please remove it; otherwise, fix it and re-purpose this issue.

**Comment by lzbj** [comment]
@mrutkows ,  I reviewed the js file, it's not commented code, just some help message about the message json structure the action will handle, so we don't need to change it, do you agree?

**Comment by lzbj** [comment]
close as comments
