### ISSUE TITLE
Typo in constructor 'NewManfiestReader' in file manifestreader.go

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#289]
Should be 'NewManifestReader' for function and references (refactor).

See https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/deployers/manifestreader.go

```
func NewManfiestReader(serviceDeployer *ServiceDeployer) *ManifestReader {
var dep ManifestReader
...
```

**Comment by mptap** [comment]
@mrutkows: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/637
