### ISSUE TITLE
Change util_test.go's "ReadUrl" test URL to a neutral address (e.g., 'apache.org') 

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#290]
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/utils/util_test.go

Currently the following address is hardcoded:
"http://www.baidu.com"

We should change this to a neutral (non-commercial) address, for example:
"https://www.apache.org/"

**Comment by mptap** [comment]
@mrutkows: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/638
