### ISSUE TITLE
Do not print "Done!" after deployment phase; use only success/failure (binary)

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#291]
Currently, we print "Done!" in most (but not all) cases after the code completes its "deployment" (phase/code).  

However, If deployment fails, we still display "Done!" (in my case for "Deploying action HelloWorld/greeting ..." when the Deployment file had an invalid namespace).  The code should not display this as it implies successful completion to the user.  Also, this "Done!" was done after the actual "status" message which was confusing.

In fact, IMO the code should not print "Done!" at all, but stick to a binary success/failure paradigm.

**Comment by zachschultz** [comment]
For Blueprints work this would be very helpful, when my wskdeploy action runs on OW it's hard to handle the case where a trigger wasn't deployed if it existed already, as the overall result from wskdeploy is still "Done!..."

**Comment by pritidesai** [comment]
No longer applicable. Prints "Success: Deployment completed successfully." on successful deployment only:

```
	if err := deployer.deployAssets(); err != nil {
		wskprint.PrintOpenWhiskError(wski18n.T(wski18n.ID_MSG_DEPLOYMENT_FAILED))
		return err
	}

	wskprint.PrintOpenWhiskSuccess(wski18n.T(wski18n.T(wski18n.ID_MSG_DEPLOYMENT_SUCCEEDED)))
```
