### ISSUE TITLE
Undeploy (on failure) should have user prompt when "interactive" mode is true

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#292]
The code logic attempts to "undeploy" code automatically when a deployment failure is detected.  

Although this is good in concept, when the user is in "interactive mode" the user should be informed of the failure and asked if they wish to "undeploy" (with a Yes/No prompt) as we do for the deployment phase.

**Comment by mrutkows** [comment]
See issue https://github.com/apache/incubator-openwhisk-wskdeploy/issues/340 which should be a pre-cursor to enabling this feature.

**Comment by lzbj** [comment]
@mrutkows , which test case you run to produce this issue? I tried the test case under  test/usecases/triggerrule/manifest.yaml, I try to deploy the same package twice, but I can't trigger any error report or undeploy logic, do I miss some important steps?

**Comment by lzbj** [comment]
However, if I try to undeploy the same package twice, I could trigger the error:
Error: /Users/dliu/go_work/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/servicedeployer.go [937]: OpenWhisk Client Error =====> The requested resource does not exist. (code 21041030) Error code: 148.

**Comment by mrutkows** [comment]
@lzbj There is no specific use case.  This was an open issue to verify (once Vincent completed the error path in the code) that we prompt the user to ask them if they want to "undeploy".  That is, do NOT assume that we should undeploy automatically.

**Comment by lzbj** [comment]
@mrutkows , ok thanks.

**Comment by pritidesai** [comment]
No longer applicable, `wskdeploy` does not undeploy any entity when deployment fails. Also deprecating interactive mode with issue #758 and force undeployment is being tracked with issue #786. Closing this.
