### ISSUE TITLE
wskdeploy should display "--help usage" if no command or manifest provided

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#294]
Currently, for both "deploy" phase and "undeploy" phase (or sub-commands) the output is as follows:
```
$ ./wskdeploy 
6:32:00 missing manifest.yaml file
```
However, it would be more helpful (pun?) if we actually told the user how to access the "help" command for wskdeploy.  Something like:
```
$ ./wskdeploy 
6:32:00 command or manifest.yaml file not found. Try "wskdeploy --help" for valid usage.
```

Again, this advice is for any top-level failure at the command syntax level. That is we should identify invalid required commands/command line options that cause an error before we can process a manifest (or deployment) file and offer better route to "help".

**Comment by mrutkows** [comment]
Another option is if we can identify just invalid command syntax, we COULD display the --help message (full usage) by default...

**Comment by lzbj** [comment]
@mrutkows , I run the latest code with your above command, I got:
Error: /Users/dliu/go_work/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go [174]: Invalid input of Yaml file =====> Missing manifest.yaml/manifest.yml file.

Usage:
  wskdeploy [flags]
  wskdeploy [command]

Available Commands:
  add         Add an action, feed, trigger or rule to the manifest
  init        Init helps you create a manifest file on OpenWhisk
  publish     Publish a package to a registry
  report      Returns summary of what's been deployed on OpenWhisk in specific namespace
  undeploy    Undeploy assets from OpenWhisk
  version     Print the version number of openwhisk-wskdeploy

Flags:
  -a, --allow-defaults       allow defaults
  -i, --allow-interactive    allow interactive prompts
      --apihost string       whisk API HOST
      --apiversion VERSION   whisk API VERSION
  -u, --auth KEY             authorization KEY
      --config string        config file (default is $HOME/.wskprops)
  -d, --deployment string    path to deployment file
  -h, --help                 help for wskdeploy
  -m, --manifest string      path to manifest file
  -n, --namespace string     namespace
  -p, --pathpath string      path to serverless project (default ".")
  -t, --toggle               Help message for toggle
  -v, --verbose              verbose output

Use "wskdeploy [command] --help" for more information about a command.

Error: /Users/dliu/go_work/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go [174]: Invalid input of Yaml file =====> Missing manifest.yaml/manifest.yml file.

**Comment by lzbj** [comment]
however, we could use SuggestFor attribute to give more help message if user typed some unknown command beyond word distance. https://github.com/apache/incubator-openwhisk-wskdeploy/pull/460

**Comment by lzbj** [comment]
close it as pr #460 merged.
