### ISSUE TITLE
wskdeploy -p finds manifest.yaml, but not manifest.yml

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#295]
The default behavior for wskdeploy when pointed to a Package directory is to look for the file "manifest.yaml"; however,  our own "usecases" name the file "manifest.yml" (i.e., .yml versus .yaml) and fail.

Please allow the code to look for both .yaml and .yml extensions by default.

For example, our test (usecase) for webhook has instructions:
```
wskdeploy -p /tests/usecases/webhook
```
However, this fails with:
```
2017/07/19 08:33:22 missing manifest.yaml file
```
because the Manifest file is actually named "manifest.yml"

**Comment by lzbj** [comment]
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/deployers/shared.go, seems all the file extension was covered.

Will take a look in the code logic to handle the parameters.

**Comment by lzbj** [comment]
https://github.com/apache/incubator-openwhisk-wskdeploy/pull/310
