### ISSUE TITLE
Implicit Runtime for Java is set to nodejs:default

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#306]
In the [manifest_parser.go](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L248), default runtime is set to nodejs. 

```
				kind := "nodejs:default"

				switch ext {
				case ".swift":
					kind = "swift:default"
				case ".js":
					kind = "nodejs:default"
				case ".py":
					kind = "python"
				}
``` 

When an action with .jar or .java extension is specified, the runtime is set to nodejs:default (snippet of the unit tests I was writing)

```
--- FAIL: TestComposeActionsForImplicitRuntimes (0.00s)
        Error Trace:    manifest_parser_test.go:510
        Error:          Not equal: 
                        expected: "java"
                        actual: "nodejs:default"
        Messages:       Expected java but got nodejs:default
FAIL
```

Here, default kind should be an empty string, and specifically check for each file extensions (.swift, .js, .py, and .jar), action file extension outside of these four options should be reported instead of setting kind for it to nodejs:default.

**Comment by lzbj** [comment]
why default kind should be a empty string? we need to consider php also as it's supported now.

**Comment by pritidesai** [comment]
We should add all supported runtimes. Also, the point of default being empty string here is in GoLang, when we initialize a struct/declare a variable, it sets the variable to its zero value which in case of string is empty string. We should add a check in ComposeActions if runtime is empty than report an error and return, do not allow further processing.

**Comment by zachschultz** [comment]
Just wskdeploy-ed a PHP action and it defaulted to `node` runtime on OpenWhisk. Should I open a new issue if my problem directly relates to this one?

**Comment by mrutkows** [comment]
@zachschultz Hi Zach, yes we should have tests in place to assure we can at least load the correct "kind" and include the latest runtime PHP.  I am of the belief that we should open more issues that are granular and worry about finding duplicates later and not hope another issue is "like mine" and assume it will be fixed.

**Comment by mrutkows** [comment]
@daisy-ycguo @lzbj 

In addition, the code should support named versions of runtimes (not just ":default").

For example, in the "triggerrule" use case, we have 
```
actions:
    greeting:
      version: 1.0
      location: src/greeting.js
      runtime: nodejs:6
```
which fails with the following error:

2017/08/15 09:58:28 error happened during unmarshal :yaml: line 9: did not find expected key
2017/08/15 09:58:28 yaml: line 9: did not find expected key
'''
since the  value "nodejs:6" was not recognized.  

We SHOULD likely have a global array of known (supported) runtimes "kinds" (both default and versioned).  This list should match what the CLI returns (as this function was added in March via https://github.com/apache/incubator-openwhisk/issues/335).

**Comment by mrutkows** [comment]
of course we need new testcases for each of these numbered cases/examples above ^^^.

**Comment by mrutkows** [comment]
@lzbj Be sure to verify that https://github.com/apache/incubator-openwhisk-wskdeploy/issues/317 (PHP runtime/kind) also is fixed by this PR.

**Comment by lzbj** [comment]
@mrutkows , is wsk cli lib provided the supported runtime/version list for us? I tried the cli command, not found yet.

**Comment by mrutkows** [comment]
@lzbj I would ask Vincent about https://github.com/apache/incubator-openwhisk/issues/335. if you need to hardcode the list for now to get it supporting all current kinds/runtimes please do so and open another issue to make it dynamic using the API (CLI).

**Comment by lzbj** [comment]
Ok, got it, thank your @mrutkows .

**Comment by mrutkows** [comment]
See PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/366#pullrequestreview-58637061

**Comment by mrutkows** [comment]
Fixed in https://github.com/apache/incubator-openwhisk-wskdeploy/pull/366
