### ISSUE TITLE
Use case of trigger rule does not configure the parameters of the action with the correct values

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#315]
In our test case of trigger rule, one action helloworld/greeting will be created with the default inputs name: Bernie and place: Vermont. However, the keys name and place have been added, but the values are not added. Here is the information of the action created, if I run the command:
 ./wskdeploy -m tests/usecases/triggerrule/manifest.yml -d tests/usecases/triggerrule/deployment.yml
{
    "namespace": "whisk.system/helloworld",
    "name": "greeting",
    "version": "0.0.1",
    "exec": {
        "kind": "nodejs:6",
        "code": "/**\n * Return a simple greeting message for someone.\n *\n * @param name A person's name.\n * @param place Where the person is from.\n */\nfunction main(params) {\n    var name = params.name || params.payload || 'stranger';\n    var place = params.place || 'somewhere';\n    return {payload:  'Hello, ' + name + ' from ' + place + '!'};\n}\n"
    },
    "annotations": [
        {
            "key": "exec",
            "value": "nodejs:6"
        }
    ],
    "parameters": [
        {
            "key": "name",
            "value": "string"
        },
        {
            "key": "place",
            "value": "string"
        }
    ],
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
    },
    "publish": false
}

**Comment by houshengbo** [comment]
@lzbj Please take a look at this issue.

**Comment by lzbj** [comment]
Ok, I'll take a look once I finished current bugs fix.

**Comment by mrutkows** [comment]
@daisy-ycguo please verify and see if the value in a Deployment.yaml were correctly being applied over the action default values.

**Comment by daisy-ycguo** [comment]
I think this issue is fixed. Below is what I found.

When I ran `wskdeploy -i -p tests/usecases/triggerrule/`, I saw below output message:
```
Packages:
Name: triggerrule
    bindings: 

  * action: greeting
    bindings: 
        - name : "Bernie"
        - place : "DC"
    annotations: 


Triggers:
* trigger: locationUpdate
    bindings: 
    annotations: 

 Rules
* rule: myRule
    - trigger: locationUpdate
    - action: triggerrule/greeting

Do you really want to deploy this? (y/N): 
```
Then I verified in OpenWhisk, trying `wsk action get triggerrule/greeting`, and I saw below message:
```
ok: got action triggerrule/greeting
{
    "namespace": "guoyingc@cn.ibm.com_dev/triggerrule",
    "name": "greeting",
    "version": "0.0.1",
    "exec": {
        "kind": "nodejs:6",
        "code": "/**\n * Return a simple greeting message for someone.\n *\n * @param name A person's name.\n * @param place Where the person is from.\n */\nfunction main(params) {\n    var name = params.name || params.payload || 'stranger';\n    var place = params.place || 'somewhere';\n    return {payload:  'Hello, ' + name + ' from ' + place + '!'};\n}\n"
    },
    "annotations": [
        {
            "key": "exec",
            "value": "nodejs:6"
        }
    ],
    "parameters": [
        {
            "key": "place",
            "value": "DC"
        },
        {
            "key": "name",
            "value": "Bernie"
        }
    ],
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
    },
    "publish": false
}
```
So I think this issue is fixed. We can close it.

**Comment by mrutkows** [comment]
@daisy-ycguo verified that this use case is now fixed with the current codebase.
