### ISSUE TITLE
Rename Marshal to marshal

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#320]
`Marshal` method in [manifest_parser.go](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L71) has only one usage inside the same `manfiest_parser.go` file. There is no need to export this method outside of `parser` package. Rename it to `marshal` to mark it as unexported.

**Comment by mptap** [comment]
@pritidesai: @mrutkows: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/643
