### ISSUE TITLE
Delete unused ComposeWskAction from Manifest Parser

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#321]
[ComposeWskAction](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L419) is defined in `manifest_parser.go` but not used anywhere inside this project. Please delete the dead code.

**Comment by mptap** [comment]
@pritidesai: @mrutkows: Looks like ComposeWskAction is no longer there. I think this issue can be closed.

**Comment by pritidesai** [comment]
Yup, `ComposeWskAction` is no longer there.
