### ISSUE TITLE
Delete unused marshal and unmarshal methods from manifest_parser.go

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#323]
[UnmarshalYAML](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L579) and [MarshalYAML](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L606) are not used anywhere in the project. Please delete these two methods to remove dead code.

**Comment by mptap** [comment]
@pritidesai: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/642

**Comment by pritidesai** [comment]
No longer applicable see PR #642
