### ISSUE TITLE
Delete dead code - deployer_parser.go

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#324]
Delete method [MarshalDeployment](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/070651b274f2d8affe6d16bfd763fc85b294b6bc/parsers/deploy_parser.go#L36) which is not used anywhere in the project.

**Comment by mptap** [comment]
@pritidesai: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/641
