### ISSUE TITLE
Rename UnmarshalDeployment to unmarshalDeployment

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#326]
`UnmarshalDeployment` method in deployment_parser.go has only one usage inside the same deployment_parser.go file. There is no need to export this method outside of parser package. Rename it to `unmarshalDeployment` to mark it as unexported.

**Comment by mptap** [comment]
@pritidesai: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/640
