### ISSUE TITLE
Unit Test - deploymentreader.go

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#328]
Add unit tests to validate methods under deployers package which are defined in [deploymentreader.go](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/deployers/deploymentreader.go).

All unit tests should go in deploymentreader_test.go under [deployers/](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/deployers)

```
// parse deployment file
func (reader *DeploymentReader) HandleYaml() error {
...
}

// bind inputs and annotations for different openwhisk entities including action, package, trigger
func (reader *DeploymentReader) BindAssets() error {
...
}
```

**Comment by daisy-ycguo** [comment]
Close as fixed.
