### ISSUE TITLE
Delete dead code - manifestreader.go

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#331]
Delete [getQualifiedName](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/deployers/manifestreader.go#L377) method which is not used anywhere in the project.

**Comment by mrutkows** [comment]
@pritidesai is this still an issue? dead code still there?

**Comment by pritidesai** [comment]
Yup I have updated link in description.

**Comment by mptap** [comment]
@pritidesai: Please could you review? https://github.com/apache/incubator-openwhisk-wskdeploy/pull/639
