### ISSUE TITLE
support more various manifest file names.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#337]
currently, we have 2 hardcoded filenames for manifest and for deployment files (i.e., manifest.yaml and .yml and deployment.yaml and .yml respectively (declared in "shared.go"). These names appear "lowercased". We need to find a way such that we can match any mixed base name such as "Manifest.yaml" or "manifest.YAML" etc. I would be happy if you want to open this as a lower priority issue to fix later.

**Comment by pritidesai** [comment]
We do support various manifest and deployment file names, outside of most used `manifest.yaml` and `deployment.yaml`.
