### ISSUE TITLE
Unit Test - cmdImp package

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#348]
Determine a list of go files and functions in those files for which we can write unit tests, create one test file per go file

Go files under [cmdImp](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/cmdImp) package:

```
rootImp.go
shared.go
undeployImp.go
```

**Comment by lzbj** [comment]
close as those files removed.

**Comment by mrutkows** [comment]
@lzbj rootImp.go and undeployImp.go are removed, but shared.go still exists.  Will change title to reflect this.
