### ISSUE TITLE
Integration Test - api-gateway

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#350]
Create an integration test for validating [api-gateway](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/usecases/api-gateway) usecase.

Integration tests are located under [tests/src/integration](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/src/integration). Create a new folder named "api-gateway" under tests/src/integration.

Remove api-gateway from usecase folder.

**Comment by mrutkows** [comment]
The use case (integration) that David submitted is deemed sufficient coverage for now.
