### ISSUE TITLE
Integration Test - Dependency (package binding)

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#355]
Add a working example of package binding and dependency section specified in [dependency under  usecases](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/usecases/dependency).

Delete dependency folder from use cases folder.

**Comment by mrutkows** [comment]
@pritidesai As you now added a GitHub dependency test from the test package we now have in incubator-openwhisk-test repo., can we close this?
