### ISSUE TITLE
Integration Test - open stack

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#357]
Create an integration test for validating [openstack](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/usecases/openstack) usecase.

Integration tests are located under tests/src/integration. Create a new folder named "openstack" under tests/src/integration.

Remove openstack from usecase folder.

**Comment by mrutkows** [comment]
Removing this use case no need to test.
