### ISSUE TITLE
Integration Test - webhook

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#359]
Create an integration test for validating [webhook](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/usecases/webhook) usecase.

Integration tests are located under tests/src/integration. Create a new folder named "webhook" under tests/src/integration.

Remove webhook from usecase folder.

**Comment by mrutkows** [comment]
For reference see discussion in https://github.com/apache/incubator-openwhisk-wskdeploy/pull/316#pullrequestreview-57257299

**Comment by pritidesai** [comment]
PR #428
