### ISSUE TITLE
Refactor yamlparser_test.go

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#361]
[yamlparser_test.go](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/yamlparser_test.go) has test cases involving manifest and deployment files. Classify those test cases and move them to manifest_parser_test.go if its manifest related test case and deployment_parser_test.go if its deployment related test case. Keep test cases as is which involves both manifest and deployment files.

**Comment by daisy-ycguo** [comment]
Close it as fixed.
