### ISSUE TITLE
Support get action from remote host through http.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#362]
We need to support action is on remote host , such as https://raw.githubusercontent.com/apache/incubator-openwhisk-catalog/master/packages/github/webhook.js, currently it only assume the file on local host.

**Comment by daisy-ycguo** [comment]
Do we need it ? @mrutkows

**Comment by lzbj** [comment]
close as we track the feature herehttps://github.com/apache/incubator-openwhisk-wskdeploy/issues/498
