### ISSUE TITLE
Bluemix Stage 1 errors creating triggers

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk-wskdeploy#365]
Using the two blueprints ([Cloudant](https://github.com/zachschultz/owbp-cloudant-trigger) and [MessageHub](https://github.com/zachschultz/owbp-message-hub-trigger)).

From OpenWhisk on Stage 1 Bluemix with no bindings or existing triggers/rules/actions I am trying to run my wskdeploy action on the [Cloudant-Swift blueprint](https://github.com/zachschultz/owbp-cloudant-trigger/blob/master/runtimes/swift/manifest.yaml)  but I am getting the following errors during trigger creation:

The offending request:
```
REQUEST:
[POST]	https://10.121.10.111:443/api/v1/namespaces/_/actions/openwhisk-cloudant/changes?blocking=true&result=false
Req Headers
{
"Authorization": [
<MY AUTH>
],
"Content-Type": [
"application/json"
]
}
Req Body
{{"authKey":"7e070f...htkMx","dbname":"wskdeploy_test","lifecycleEvent":"CREATE","triggerName":"/_/data-inserted-trigger"}
}
```

The response:
```
RESPONSE:Got response with code 502
Resp Headers
{
"Access-Control-Allow-Headers": [
"Authorization, Content-Type"
],
"Access-Control-Allow-Origin": [
"*"
],
"Connection": [
"keep-alive"
],
"Content-Length": [
"708"
],
"Content-Type": [
"application/json; charset=UTF-8"
],
"Date": [
"Thu, 17 Aug 2017 20:54:50 GMT"
],
"Server": [
"nginx/1.11.13"
]
}
Response body size is 708 bytes
Response body received:
{
"duration": 1005,
"name": "changes",
"subject": "zachary.schultz@ibm.com",
"activationId": "cd19f4665b1e4672a788a8c6405b6648",
"publish": false,
"annotations": [{
"key": "limits",
"value": {
"timeout": 90000,
"memory": 256,
"logs": 10
}
}, {
"key": "path",
"value": "whisk.system/cloudant/changes"
}],
"version": "0.0.120",
"response": {
"result": {
"error": {
"error": "error creating cloudant trigger.",
"message": "Document update conflict."
}
},
"success": false,
"status": "application error"
},
```

I also see an action after that failed, which shows this:

```
{
    "error": {
        "error": "error creating cloudant trigger.",
        "message": "Document update conflict."
    }
}
Logs:
cloudant: Error invoking whisk action: 409 { error: 'error creating cloudant trigger.',
message: 'Document update conflict.' }
```
On subsequent attempts to run `wskdeploy`, now on the "unclean" OpenWhisk, I see this in my wskdeploy output:

```
stderr from wskDeploy:
2017/08/17 20:59:18 Deploying package cloudant-trigger ...
2017/08/17 20:59:18 Done!
2017/08/17 20:59:18 Deploying package bindingopenwhisk-cloudant ...
2017/08/17 20:59:18 Done!
2017/08/17 20:59:18 Deploying action cloudant-trigger/process-change ...
2017/08/17 20:59:18 Done!
2017/08/17 20:59:18 Deploying action cloudant-trigger/process-change-cloudant-sequence ...
2017/08/17 20:59:18 Done!
2017/08/17 20:59:18 Deploying trigger feed data-inserted-trigger ...
2017/08/17 20:59:18 Got error creating trigger with error message: resource already exists (code 1349070) and error code: 153.
```

So it appears as thought the trigger couldn't be successfully created, but a non-working one is created in its place. 

Running all of the above on normal production Bluemix/OpenWhisk results in no errors.

**Comment by daisy-ycguo** [comment]
@zachschultz help me understand when you are saying "a clean OpenWhisk on Stage 1 Bluemix with no bindings or existing triggers/rules/actions" do you mean "/whisk.system/cloudant" is not installed in your clean OpenWhisk ? I think, openwhisk-cloudant-trigger has dependencies on "/whisk.system/cloudant", you need to install whisk.system package before you run this case.

**Comment by zachschultz** [comment]
@daisy-ycguo Sorry about the confusion, what I meant was that I just created a new space and org on Bluemix and used the OpenWhisk from there

**Comment by daisy-ycguo** [comment]
@zachschultz I checked this case in my environment, but I didn't meet with errors. Please refer to my steps and let me know what happens in your environment. Thank you.

Have a clean OpenWhisk environment firstly.

1. Create a Cloudant service in Bluemix, with the service name as "openwhisk-cloudant", creating a database named "cats".
2. Check out your source code `zachschultz/owbp-cloudant-trigger`
3. Set environment values ( make sure to run this step and set the correct values. Refer to [this page](https://console.bluemix.net/docs/services/Cloudant/getting-started.html#getting-started-with-cloudant) to get the correct values of HOSTNAME,USERNAME and PASSWORD.)
```
export CLOUDANT_HOSTNAME=f24a57b7-0167-bluemix.cloudant.com
export CLOUDANT_DATABASE="cats"
export CLOUDANT_USERNAME="f24a57b7-0167-bluemix"
export CLOUDANT_PASSWORD="24b84123bd42b1d3e"
```
4. Run WskDeploy:
`wskdeploy -m ~/workspace/owbp-cloudant-trigger/runtimes/node/manifest.yaml`
Then you will see a deployment success message:
```
2017/08/22 06:16:25 Deploying package cloudant-trigger ... 
2017/08/22 06:16:26 Done!
Deploying dependency openwhisk-cloudant ... 
2017/08/22 06:16:26 Deploying package bindingopenwhisk-cloudant ... 
2017/08/22 06:16:27 Done!
2017/08/22 06:16:27 Deploying action cloudant-trigger/process-change ... 
2017/08/22 06:16:27 Done!
2017/08/22 06:16:27 Deploying action cloudant-trigger/process-change-cloudant-sequence ... 
2017/08/22 06:16:27 Done!
2017/08/22 06:16:27 Deploying trigger feed data-inserted-trigger ... 
Done!
Deploying rule log-change-rule ... Done!

Deployment completed successfully.
```
5. Begin streaming the OpenWhisk activation log in a second terminal window by `wsk activation poll`
6. add a document to `cats` database from the Cloudant WebUI in Bluemix, 
```
{
  "_id": "5899d103fbd5a7770fb4d34105b8277e",
  "name": "hello world",
  "color": "blue"
}
```
7. Check the OpenWhisk activation log, you will see the successful invocation:
```
Activation: process-change (0f1995b7e8ae410498764be8653c12cd)
[
    "2017-08-22T06:33:06.910107729Z stdout: hello world",
    "2017-08-22T06:33:06.910175137Z stdout: blue",
    "2017-08-22T06:33:06.910184627Z stdout: A blue cat named hello world was added."
]

Activation: read (7eae3fbf35f441aeb06392901e3ce753)
[
    "2017-08-22T06:33:06.832994483Z stdout: success { _id: '5899d103fbd5a7770fb4d34105b8277e',",
    "2017-08-22T06:33:06.833026012Z stdout: _rev: '2-6ebc654e16f02a8dd9b1dc62d4e5df74',",
    "2017-08-22T06:33:06.83303362Z  stdout: name: 'hello world',",
    "2017-08-22T06:33:06.833039425Z stdout: color: 'blue' }"
]

Activation: process-change-cloudant-sequence (91e773991eb540409fe9d5bfbaa32fa4)
[
    "7eae3fbf35f441aeb06392901e3ce753",
    "0f1995b7e8ae410498764be8653c12cd"
]

Activation: log-change-rule (c2e1d7c4b3294d47b14fd6d7d749dd04)
[]

Activation: data-inserted-trigger (590d300c97d142f8b055ff8bd6261af8)
[]
```

Regards
Daisy

**Comment by zachschultz** [comment]
@daisy-ycguo thank you! For some reason, now I am able to get the triggers and rules working when I push data to cloudant/message-hub, however when I run wskdeploy for the message-hub blueprint I'm still getting the extra action that looks like this: 

```
Error creating trigger: {
  "name": "StatusCodeError",
  "statusCode": 500,
  "message": "500 - \"Error: Document update conflict.\"",
  "error": "Error: Document update conflict.",
  "options": {
    "method": "PUT",
    "url": "https://10.121.10.111/api/v1/web/whisk.system/messagingWeb/messageHubFeedWeb.http",
    "rejectUnauthorized": false,
    "json": true,
    "body": {
      // REST OF PERSONAL DATA OMITTED (USER/PASS/etc.)
      "triggerName": "/zachary.schultz_ow/message-received-trigger",
    },
    "headers": {
        "Content-Type": "application/json",
        "Accept": "text/plain",
        "User-Agent": "whisk"
    },
    "simple": true,
    "resolveWithFullResponse": false,
    "transform2xxOnly": false
  },
  "response": {
    "statusCode": 500,
    "body": "Error: Document update conflict.",
    "headers": {
      "server": "nginx/1.11.13",
      "date": "Wed, 23 Aug 2017 19:49:56 GMT",
      "content-type": "text/plain",
      "content-length": "32",
      "connection": "close",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "OPTIONS, GET, DELETE, POST, PUT, HEAD, PATCH",
      "access-control-allow-headers": "Authorization, Content-Type"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "10.121.10.111",
        "port": 443,
        "hostname": "10.121.10.111",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/api/v1/web/whisk.system/messagingWeb/messageHubFeedWeb.http",
        "path": "/api/v1/web/whisk.system/messagingWeb/messageHubFeedWeb.http",
        "href":       "https://10.121.10.111/api/v1/web/whisk.system/messagingWeb/messageHubFeedWeb.http"
      },
      "method": "PUT",
      "headers": {
        "Content-Type": "application/json",
        "Accept": "text/plain",
        "User-Agent": "whisk",
        "content-length": 707
      }
    }
  }
}
```

Everything seems to work though, but I am still getting that message

**Comment by mrutkows** [comment]
@zachschultz  @daisy-ycguo Daisy, did you test this with BlueWhisk or local OpenWhisk?  You steps indicate "Have a clean OpenWhisk environment"  this implies local (not Bluemix OpenWhisk unless you mean the account has not Actions/Triggers/Rules, etc.)?

**Comment by daisy-ycguo** [comment]
@mrutkows I'm using OpenWhisk on Bluemix, i.e. BlueWhisk. "Have a clean OpenWhisk env" here means there is no Actions/Triggers/Rules under this account and namespace. That is to make sure to not to create any duplicated action/trigger/rule.

**Comment by zachschultz** [comment]
@mrutkows sorry about the confusion, adjusted my original issue comment to hopefully clear it up. @daisy-ycguo covered what I actually meant.

**Comment by daisy-ycguo** [comment]
@zachschultz Is this issue fixed ? We have opened another issue #399 to print out warning messages and promoting if user wants to process when environment variables in YAML files are empty.

**Comment by zachschultz** [comment]
@daisy-ycguo I can't reproduce the issue anymore, so I would say it's fixed!

**Comment by daisy-ycguo** [comment]
Thank you, @zachschultz . I will close it. When you meet with it again, we can reopen it.
