### ISSUE TITLE
Deployment.yaml files all use "package" key, spec. has "packages"

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#393]
In every test's Deployment.yaml (and of course the code supports this) the key "package:" is used; however, the spec. has always had the plural "packages:" this key name change will impact all files.

I would be happy to support both "package" (singular) and "packages" (plural) as long as we display a warning, but our tests should use what is in the spec.

**Comment by mrutkows** [comment]
@pritidesai can you please look at changing this globally; see if we can allow (in some deprecated manner, perhaps issue a WARNING message) and allow the "package" (singular) to be supported for some period of time and mark/comment the code to indicated we should remove this at a later date (perhaps open a low priority issue as well to remind us).

**Comment by pritidesai** [comment]
Please close this as its fixed with PR #418

**Comment by mrutkows** [comment]
Priti fixed in PR 418 not only fixed the warning, but also the actual root of the problem.  WTG!
