### ISSUE TITLE
Cross-compiling wskdeploy

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk-wskdeploy#400]
I see a lot of issues regarding this but none seem to explicitly state how it's done. Running `./gradlew distDocker` I noticed that this command is run `docker build --build-arg WSKDEPLOY_OS=mac --build-arg WSKDEPLOY_ARCH=amd64 -t wskdeploy /Users/zach/dev/incubator-openwhisk-wskdeploy` and it seems like you're able to change the `WSKDEPLOY_OS` and `WSKDEPLOY_ARCH` to build for whatever platform you desire.

Still, even using the above I notice that no `bin/` directory is created, so there's no use. Manually changing `build.gradle`'s function `getOsName` to return `'linux'` did the trick however.

If the above is the correct method for cross-compilation, I think it would be very useful to display this in the readme/docs for other users to see how it is done.

**Comment by mrutkows** [comment]
@priti @zachschultz as Priti described, we will need to document how to set the project property "crossCompileWSKDEPLOY" and how this affects Dockerfile build ARGS (WSKDEPLY_OS and WSKDEPLOY_ARCH); specifically, the default behavior or build.gradle automatically sets these to the local OS environment.

```
if(!project.hasProperty('crossCompileWSKDEPLOY') \|\| project.crossCompileWSKDEPLOY == "false") {
   res = ["WSKDEPLOY_OS=${local_os}", "WSKDEPLOY_ARCH=${local_arch}"]
 } else {
   res = ["WSKDEPLOY_OS=mac linux windows", "WSKDEPLOY_ARCH=386 amd64"]
```

**Comment by mrutkows** [comment]
@priti has volunteered to update the documentation after having researched this issue

**Comment by mrutkows** [comment]
@houshengbo please verify with Zach that he can compile now and we can close this.

**Comment by houshengbo** [comment]
This one has been fixed by the updates of readme.
