### ISSUE TITLE
Unit test of TestParseManifestForSingleLineParams failing

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-wskdeploy#405]
=== RUN   TestParseManifestForSingleLineParams
2017/08/28 23:03:51 error happened during unmarshal :yaml: unmarshal errors:
  line 25: cannot unmarshal !!str `` into parsers.Parameter
  line 26: cannot unmarshal !!str `` into parsers.Parameter
2017/08/28 23:03:51 yaml: unmarshal errors:
  line 25: cannot unmarshal !!str `` into parsers.Parameter
  line 26: cannot unmarshal !!str `` into parsers.Parameter
2017/08/28 23:03:51 Error happened during execution, please type 'wskdeploy -h' for help messages.
FAIL	github.com/apache/incubator-openwhisk-wskdeploy/parsers	0.015s

**Comment by houshengbo** [comment]
@daisy-ycguo @lzbj Did you see this issue?

**Comment by daisy-ycguo** [comment]
@houshengbo it didn't have any issues in my laptop.
```
$ make test | grep 'TestParseManifestForSingleLineParams'
=== RUN   TestParseManifestForSingleLineParams
--- PASS: TestParseManifestForSingleLineParams (0.00s)
```

**Comment by lzbj** [comment]
I got the same issue.
Installing dependencies
go get -d -t ./...
Testing
go test ./... -tags=unit
?   	github.com/apache/incubator-openwhisk-wskdeploy	[no test files]
ok  	github.com/apache/incubator-openwhisk-wskdeploy/cmd	1.254s
ok  	github.com/apache/incubator-openwhisk-wskdeploy/deployers	0.013s
Error:  <nil>
Filepath: "  "
Package:  {   [] map[]     map[] map[] map[] map[] map[] map[] map[]}
PackageName: "  "
Number of Actions:  0
Actions:  map[]
2017/08/29 16:04:25 error happened during unmarshal :yaml: unmarshal errors:
  line 25: cannot unmarshal !!str `` into parsers.Parameter
  line 26: cannot unmarshal !!str `` into parsers.Parameter
2017/08/29 16:04:25 yaml: unmarshal errors:
  line 25: cannot unmarshal !!str `` into parsers.Parameter
  line 26: cannot unmarshal !!str `` into parsers.Parameter
2017/08/29 16:04:25 Error happened during execution, please type 'wskdeploy -h' for help messages.
FAIL	github.com/apache/incubator-openwhisk-wskdeploy/parsers	0.014s
?   	github.com/apache/incubator-openwhisk-wskdeploy/tests/src/integration/common	[no test files]
ok  	github.com/apache/incubator-openwhisk-wskdeploy/utils	0.054s
?   	github.com/apache/incubator-openwhisk-wskdeploy/wski18n	[no test files]
make: *** [test] Error 1

**Comment by lzbj** [comment]
Raise the level to get some attention, since it will slow down the development.

**Comment by houshengbo** [comment]
@lzbj Strangely travis does not report this error, but it really exists when I run make test locally. Is there something wrong with manifest_validate_singleline_params.yaml?

**Comment by lzbj** [comment]
@houshengbo , correct, so I doubt we hit a yaml lib bug or even a golang bug perhaps, need to dig deeper in this.

**Comment by houshengbo** [comment]
@lzbj Line 25 and Line 26 put '' and "" as the values. It seems the parser does not read them correctly.

**Comment by daisy-ycguo** [comment]
@lzbj @houshengbo interesting issue. I run under ubuntu and it works fine.

**Comment by houshengbo** [comment]
@daisy-ycguo It is valid in mac. I tried ubuntu as well, there is no issue for linux.

**Comment by lzbj** [comment]
@pritidesai  is our UT expert, please could you help take a look @pritidesai

**Comment by pritidesai** [comment]
@lzbj thanks for recognition :) you will be surprised to know I have no QA background 👎 

didn't find any issues while running that test on mac:

```
go test ./parsers/ -tags=unit -run=TestParseManifestForSingleLineParams -v
=== RUN   TestParseManifestForSingleLineParams
--- PASS: TestParseManifestForSingleLineParams (0.00s)
PASS
ok      github.com/apache/incubator-openwhisk-wskdeploy/parsers 0.021s
```

**Comment by lzbj** [comment]
thank you @pritidesai , it seems my env problems.
I run the same command, got the output.
 go test ./parsers/ -tags=unit -run=TestParseManifestForSingleLineParams -v
=== RUN   TestParseManifestForSingleLineParams
2017/08/30 17:14:34 error happened during unmarshal :yaml: unmarshal errors:
  line 25: cannot unmarshal !!str `` into parsers.Parameter
  line 26: cannot unmarshal !!str `` into parsers.Parameter
2017/08/30 17:14:34 yaml: unmarshal errors:
  line 25: cannot unmarshal !!str `` into parsers.Parameter
  line 26: cannot unmarshal !!str `` into parsers.Parameter
2017/08/30 17:14:34 Error happened during execution, please type 'wskdeploy -h' for help messages.
exit status 1
FAIL    github.com/apache/incubator-openwhisk-wskdeploy/parsers 0.011s

**Comment by lzbj** [comment]
I used go1.9

**Comment by pritidesai** [comment]
@lzbj can you please check if this issue is resolved for you?

**Comment by lzbj** [comment]
@pritidesai , thank you, yes, it's fixed after I upgrade the yaml lib version, so close it.
