### ISSUE TITLE
typo in error message 

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#411]
```
log.Println("the runtime it not supported by Openwhisk platform.")
```

should be

```
log.Println("the runtime is not supported by Openwhisk platform.")
```

In manifest parser at: https://github.com/apache/incubator-openwhisk-wskdeploy/blob/37925e44a5772e5540c984465661e606427695e7/parsers/manifest_parser.go#L309

**Comment by daisy-ycguo** [comment]
Fixed and closed.
