### ISSUE TITLE
dependent packages requires manifest.yml and doesn't support manifest.yaml

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#415]
wskdeploy does not support dependent packages which has manifest.yaml file. It only deploys dependent package with manifest.yml. Please add support for manifest.yaml. Refer to integration test on dependency for more info: https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/src/integration/dependency

**Comment by lzbj** [comment]
@pritidesai , I can't reproduce this issue, could you help confirm.
I forked your repo here.https://github.com/lzbj/openwhisk-app
then I changed the yaml like this:
diff --git a/tests/src/integration/dependency/manifest.yaml b/tests/src/integration/dependency/manifest.yaml
index f76390d..e85bc4b 100644
--- a/tests/src/integration/dependency/manifest.yaml
+++ b/tests/src/integration/dependency/manifest.yaml
@@ -2,7 +2,7 @@ package:
   name: TestGitHubDependency
   dependencies:
     openwhisk-app:
-      location: github.com/pritidesai/openwhisk-app
+      location: github.com/lzbj/openwhisk-app
   triggers:
     trigger1:


THen I run the deploy.

2017/08/30 14:15:18 Unmarshal Openwhisk info from internet
2017/08/30 14:15:18 The URL is https://openwhisk.ng.bluemix.net/api, selected from .wskprops
2017/08/30 14:15:18 The auth key is set, selected from .wskprops
2017/08/30 14:15:18 The namespace is david.liu@cn.ibm.com_dliu, selected from .wskprops
2017/08/30 14:15:21 Deploying package TestGitHubDependency ... 
2017/08/30 14:15:22 Done!
Deploying dependency openwhisk-app ... 
2017/08/30 14:15:22 Deploying package openwhisk-app ... 
2017/08/30 14:15:23 Done!
2017/08/30 14:15:23 Deploying action openwhisk-app/helloworld ... 
2017/08/30 14:15:24 Done!
2017/08/30 14:15:24 Deploying action openwhisk-app/hello ... 
2017/08/30 14:15:24 Done!
Done!
Done!
Done!
Deploying rule rule1 ... Done!
Deploying rule rule2 ... Done!
2017/08/30 14:15:26 
Deployment completed successfully.

**Comment by lzbj** [comment]
I have already changed the yaml file in my repo to .yaml, did I miss some steps to reproduce?

**Comment by pritidesai** [comment]
nope @lzbj doesn't look like you missed anything, I am not able to reproduce as well, but now running into different issue, @daisy-ycguo can you please check? I just replaced `location` with `function` in [manifest file](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/dependency/manifest.yaml#L5). 

```
go test ./tests/src/integration/dependency/ -tags=integration -run=TestDependency -v
=== RUN   TestDependency
wskdeploy.Path is wskdeploy
==> Executing: wskdeploy -m /Users/pritidesai/Documents/goworkspace/src/github.com/apache/incubator-openwhisk-wskdeploy/tests/src/integration/dependency/manifest.yaml -d 
==> Output: 2017/08/30 01:01:48 Unmarshal Openwhisk info from internet
2017/08/30 01:01:48 The URL is https://openwhisk.ng.bluemix.net/api, selected from .wskprops
2017/08/30 01:01:48 The auth key is set, selected from .wskprops
2017/08/30 01:01:48 The namespace is ****, selected from .wskprops
2017/08/30 01:01:48 Deploying package TestGitHubDependency ... 
2017/08/30 01:01:48 Done!
Done!
Done!
Deploying rule rule2 ... 2017/08/30 01:01:48 Got error creating rule with error message: The requested resource does not exist. (code 40237943) and error code: 148.
2017/08/30 01:01:48 Got error activating rule with error message: The requested resource does not exist. (code 40237946) and error code: 148.
Done!
Deploying rule rule1 ... 2017/08/30 01:01:49 Got error creating rule with error message: The requested resource does not exist. (code 40237959) and error code: 148.
2017/08/30 01:01:49 Got error activating rule with error message: The requested resource does not exist. (code 40237969) and error code: 148.
Done!
2017/08/30 01:01:49 
Deployment completed successfully.

wskdeploy.Path is wskdeploy
==> Executing: wskdeploy undeploy -m /Users/pritidesai/Documents/goworkspace/src/github.com/apache/incubator-openwhisk-wskdeploy/tests/src/integration/dependency/manifest.yaml -d 
==> Output: 2017/08/30 01:01:49 Unmarshal Openwhisk info from internet
2017/08/30 01:01:49 The URL is https://openwhisk.ng.bluemix.net/api, selected from .wskprops
2017/08/30 01:01:49 The auth key is set, selected from .wskprops
2017/08/30 01:01:49 The namespace is **** selected from .wskprops
Removing trigger trigger1 ... Done!
Removing trigger trigger2 ... Done!
Removing rule rule2 ... 2017/08/30 01:01:49 Got error deleting rule with error message: The requested resource does not exist. (code 40238025) and error code: 148.
Removing rule rule1 ... 2017/08/30 01:01:50 Got error deleting rule with error message: The requested resource does not exist. (code 40238031) and error code: 148.
Removing package TestGitHubDependency ... Done!

Deployment removed successfully.

--- PASS: TestDependency (2.45s)
PASS
ok      github.com/apache/incubator-openwhisk-wskdeploy/tests/src/integration/dependency        2.471s
```

**Comment by daisy-ycguo** [comment]
@pritidesai  In the specification, the properties under `dependencies` are: `location`, `version` and `inputs`. So please don't change it to `function`. Our code doesn't support `function` under `dependencies`. We only support `function` under `action`.

**Comment by mrutkows** [comment]
@lzbj @priti Please see that we no longer use hardcoded "manifest.yaml" in any function when possible.  See grep:

``
grep -r "\"manifest.yaml" . --include=*.go
./cmd/add.go:		parsers.Write(maniyaml, "manifest.yaml")
./cmd/add.go:		parsers.Write(maniyaml, "manifest.yaml")
./cmd/add.go:		parsers.Write(maniyaml, "manifest.yaml")
./cmd/init.go:		parsers.Write(maniyaml, "manifest.yaml")
./cmd/root.go:		if _, err := os.Stat(path.Join(projectPath, "manifest.yaml")); err == nil {
./deployers/shared.go:const ManifestFileNameYaml = "manifest.yaml"
./parsers/manifest_parser.go:	if _, err := os.Stat("manifest.yaml"); err == nil {
./parsers/manifest_parser.go:		dat, _ := ioutil.ReadFile("manifest.yam")

```

**Comment by pritidesai** [comment]
verified hardcoding of manifest and deployment is gone with PR #424

**Comment by pritidesai** [comment]
```
/deployers/whiskclient.go:    MANIDESTFILE = "manifest.yml"

./cmd/root.go:          } else if _, err := os.Stat(path.Join(projectPath, "deployment.yml")); err == nil {
./cmd/root.go:          } else if _, err := os.Stat(path.Join(projectPath, "deployment.yml")); err == nil {
./deployers/whiskclient.go:    DEPLOYMENTFILE = "deployment.yml"

./cmd/root.go:          if _, err := os.Stat(path.Join(projectPath, "deployment.yaml")); err == nil {
./cmd/root.go:          if _, err := os.Stat(path.Join(projectPath, "deployment.yaml")); err == nil {
```

**Comment by pritidesai** [comment]
addressing `function` vs `location` in issue https://github.com/apache/incubator-openwhisk-wskdeploy/issues/427
