### ISSUE TITLE
wskdeploy doesn't work with latest code merges.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#416]
is anyone face the issue.
when I run wskdeploy -m /path/to/manifest, I got a error.
2017/08/30 11:44:26 Unmarshal Openwhisk info from internet
2017/08/30 11:44:26 Missing authentication key
2017/08/30 11:44:26 Error happened during execution, please type 'wskdeploy -h' for help messages.
exit status 1

@daisy-ycguo @houshengbo @pritidesai , can you double confirm, when I try to resolve the issue https://github.com/apache/incubator-openwhisk-wskdeploy/issues/415

**Comment by lzbj** [comment]
@daisy-ycguo, said she can't build with latest codes.

**Comment by daisy-ycguo** [comment]
@lzbj 
I updated to latest wskclient, and I can build now. I deployed a cloudant-trigger test case, it worked for me.

**Comment by lzbj** [comment]
ok, got it, I didn't update my cli lib, yes it works now, close it.
Thanks a lot @daisy-ycguo .
