### ISSUE TITLE
New output messages from wskdeply

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#417]
Do we really want to print these messages ? Or they are debug messages which should be removed ?

```
$ ./wskdeploy -i -m ~/workspace/owbp-cloudant-trigger/runtimes/node/manifest.yaml
2017/08/30 06:12:53 Unmarshal Openwhisk info from internet
2017/08/30 06:12:53 The URL is https://openwhisk.ng.bluemix.net/api, selected from .wskprops
2017/08/30 06:12:53 The auth key is set, selected from .wskprops
2017/08/30 06:12:53 The namespace is _, selected from manifest.yml
```

**Comment by mrutkows** [comment]
As part of Vincent's work I hope we have something like a "printWarning()" printError() printInfo() printTrace() in a shared package/module (with standard formatting that allow timestamp, module, line number for trace and YAML file/line number if parser finds an error in a YAML file.  We can do what the CLI does and print trace if an Environment Variable is set to value > 0.  @houshengbo

**Comment by mrutkows** [comment]
If we have ^^^ then we can decide which ones are info, verbose and which are trace...  and turn on verbose when user sets flag, turn on trace if env. variable is set to non-zero (true) value.

**Comment by mrutkows** [comment]
@daisy-ycguo @pritidesai @houshengbo for now the more messages the better as we work down our backlog and we can move most to a printTrace() or printVerbose() type method later.

**Comment by daisy-ycguo** [comment]
Close it as it's not valid now.
