### ISSUE TITLE
runtime swift vs swift:2 vs swift:3.1.1

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#429]
I am writing an action and have set runtime to `swift` or `swift:2` which fails:

```
2017/08/31 14:09:46 Got error creating action with error message: The 'swift' runtime is no longer supported. You may read and delete but not update or invoke this action. (code 196) and error code: 144.
```
This error disappears and action is deployed when runtime is set to `swift:3.1.1`. 

Does openwhisk support swift:2? One of the blog posts says "If you have any Swift v2 actions, you will want to migrate those to the Swift v3 runtime."

**Comment by rabbah** [comment]
Not anymore.

**Comment by lzbj** [comment]
close as rabbah's comments.
