### ISSUE TITLE
Add --strict flag to deploy actions with specified runtimes 

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#443]
As a result of issue #442, we are adding ability in wskdeploy to create actions with latest version of specified runtimes if the user specified version is no longer supported. In case, when user doesn't want `wskdeploy` to **fix** the version for them instead stop the deployment, this kind of flag will be useful.

**Comment by lzbj** [comment]
@pritidesai , sorry I'm a little bit confused about your description, so we should add a --strict flag to let user define any version they want right?

**Comment by mrutkows** [comment]
Closed by PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/541
