### ISSUE TITLE
wskdeploy build error on the latest code base

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#451]
when I run `go build -o wskdeploy` I will get
```
# github.com/apache/incubator-openwhisk-wskdeploy/parsers
parsers/deploy_parser.go:27: undefined: yaml.UnmarshalStrict
parsers/manifest_parser.go:62: undefined: yaml.UnmarshalStrict
```

I need help @pritidesai 
Shall I install anything in my env ?

**Comment by daisy-ycguo** [comment]
I'm using Ubuntu and Go 1.8

**Comment by pritidesai** [comment]
@daisy-ycguo I have PR #452 to update godep file which should solve your problem.

**Comment by daisy-ycguo** [comment]
It works now, @pritidesai .

rm -rf $GOFOLDER

It works now. Thank you @pritidesai 

```
rm -rf $GOPATH/src/gopkg.in/yaml.v2
go get gopkg.in/yaml.v2
```

I will close this one.
