### ISSUE TITLE
Go External Library Versions 

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#452]
Do we have a way to specify which version of external go libraries are supported by `wskdeploy`? If we don't, please add a support to pull external libraries with specified versions, it is possible that `wskdeploy` might not be compatible with specific versions of external libraries.

**Comment by csantanapr** [comment]
We use Godeps to specified dependencies https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/Godeps/Godeps.json

**Comment by pritidesai** [comment]
Thanks @csantanapr I have updated go dependency for YAML as we switched to using UnmarshalStrict instead of Unmarsh, with PR #454

**Comment by mrutkows** [comment]
@pritidesai since Vincent and you both updated the godeps for YAML library, do we need to keep this issue open?

**Comment by mrutkows** [comment]
Fixed with PRiti's PR https://github.com/apache/incubator-openwhisk-wskdeploy/commit/68d74d52f489aff69630f422ac2d3ccc21cf635f#diff-681659ab9abb4b4883e78e8aaa980dba
