### ISSUE TITLE
Use Case - cloudant feed

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#473]
Please add a realistic cloudant use case which can than be used as part of integration test. We don't have any manifest/deployment files for cloudant (showing how to configure credentials: username, password, url, etc) in our repo.

Priority: High
Category: use case, enhancement

**Comment by mrutkows** [comment]
See advice on PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/486
