### ISSUE TITLE
Create a README on Credential Precedence

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#490]
Lately, there has been some confusion on the order of reading credentials from CLI/manifest/deployment/.wskprops/whisk.properties. 

Refer to issue #471 and create a readme file with simple usage and examples.

**Comment by mrutkows** [comment]
Please review the document I am working on in my private repo. and is part of WIP PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/489

**Comment by mrutkows** [comment]
fixed in 489
