### ISSUE TITLE
manifest_basic_tar_grammar.yaml also tests feeds and api grammar; split them out

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#494]
Originally, this test file was supposed to test basic **Trigger**-**Action**-**Rule** (TAR) grammars.  Over time, **feeds** and now **api** grammars were added to the same test file.  

As we add more "entities" like **feeds** and **apis** that build on more basic ones like **triggers**, etc. we should look to test them in their own manifest files.

This will improve testing granularity; please split out **feeds** grammar unit tests and **api** grammar unit tests into separate manifests.

**Comment by pritidesai** [comment]
this file doesnt exists anymore ...

```
find . -name "manifest_basic_tar_grammar.yaml" -type f
```
