### ISSUE TITLE
We don't support concatenation of an environment value and a string

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#501]
We don't support environment using like this: $CLOUDANT_USERNAME.cloudant.com. `CLOUDANT_USERNAME.cloudant.com` will be treated as a whole part. And it will report an error "WARNING: Missing Environment Variable CLOUDANT_USERNAME.cloudant.com."

Do we need to support this feature ?

**Comment by mrutkows** [comment]
@daisy-ycguo I know this is something other YAML-based orchestration and deployment files support. We should discuss this.
