### ISSUE TITLE
Cloudant case failed

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#502]
Deployment of https://github.com/zachschultz/owbp-cloudant-trigger/runtimes/node/manifest.yaml will get an error:
```
Error: /home/daisy/gofolder/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/servicedeployer.go [535]: OpenWhisk Client Error =====> The following application error was received: {} Error code: 246.
```

Need to look at this issue.

**Comment by mrutkows** [comment]
```
public static final int APP_ERROR       = 246;      // 502 - 256 = 246
public static final int TIMEOUT = 246; // 502 (GATEWAY_TIMEOUT) - 256 = 246
```

**Comment by mrutkows** [comment]
@daisy-ycguo assume we want to track this as being associated with issue https://github.com/apache/incubator-openwhisk-wskdeploy/issues/473

**Comment by mrutkows** [comment]
@daisy-ycguo @pritidesai Daisy, Priti saw general 'failure' error messages (not nil, but empty) when attempting to delete triggers.  Please see her comments here: https://github.com/apache/incubator-openwhisk-wskdeploy/pull/486

Not sure where you are seeing your error.  My assumption was not on a Trigger delete (undeploy), but on deployment.

**Comment by mrutkows** [comment]
@daisy-ycguo Also, your link is broken as Zach changed his account; you will need to ask Belinda where she moved his test code to.

**Comment by daisy-ycguo** [comment]
The root cause of this issue is that I set an invalid value to `$CLOUDANT_USERNAME`. After I set `$CLOUDANT_USERNAME` to the correct value, it can be deployed successfully.

I think we should report correct error message other than `The following application error was received: {} Error code: 246.`. This one has been tracked by issue #510. 

So close this one.
