### ISSUE TITLE
Only show full  path/filename on error/warning messages if -v (--verbose) set to True

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#505]
I like very much that we display the filename after the word "Error: "; however, it pushes the error code and description off the screen.

```
Error: /Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go [235]: Invalid input of Yaml file =====> Missing manifest.yaml/manifest.yml file.
```

is there a way to detect if -v --verbose flag is set and in this case display the full path/file name (as it does now), buf if verbose flag is NOT set then we only display the relative path name?

for example, if -v or --verbose were NOT set we would see:
```
Error: /cmd/root.go [235]: Invalid input of Yaml file =====> Missing manifest.yaml/manifest.yml file.
```

**Comment by pritidesai** [comment]
Must have been fixed at some point:

```
./wskdeploy  -v
Error: root.go [140]: [ERROR_MANIFEST_FILE_NOT_FOUND]: File: [incubator-openwhisk-wskdeploy]: Manifest file not found at path [<full path>].
```
