### ISSUE TITLE
Change term "unmarshal errors" on Error output use 'parser errors' and clean up

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#506]
Currently, we display something like the following for YAML parsing errors:
```
Error: /deployers/manifestreader.go [50]: Invalid input of Yaml file =====> /Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/parsers/manifest_parser.go [98]:
 Failed to parse the yaml file docs/examples/manifest_hello_world.yaml
 =====> yaml: unmarshal errors:
  field hello_world_package not found in struct parsers.Package: Line 3, its neighbour lines, or the lines on the same level.
```

However, the term "unmarshall" is not a user-friendly term.  Instead, we should display something like:
```
...
 =====> YAML: Parsing errors:
  field hello_world_package not found in struct parsers.Package: Line 3, its neighbour lines, or the lines on the same level.
```

Please also, somehow denote that the name ```hellow_world_package``` was treated as a keyname (word from spec. NOT use the word 'field'.  Also, we should not have the word 'struct' appear pr "Parsers." (as these are code terms, that we MIGHT display in --verbose mode ONLY), but the normal end-user would like to just know the name "Package".

Perhaps something like:
```
 =====> YAML: Parsing errors:
  key name [hello_world_package] not a valid key for a [Package]: Line 3, its neighbour lines, or the lines on the same level.
```

also the English US spelling is 'neighbor'.

**Comment by houshengbo** [comment]
@mrutkows 
Messages like
field hello_world_package not found in struct parsers.Package
are coming from the error raised by the yaml library. We are unable to specify key name and package name on a more granular level.
