### ISSUE TITLE
Warning message does not highlight key words from grammar (e.g., 'package')

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#557]
The warning we display when the key word 'package' is found in a manifest (or deployment file) looks like this:
```
WARNING: using package inside of manifest file will soon be deprecated, please use packages instead.
```
1) we should somehow highlight the words in the sentence that are "key names"...
2) we are missing the word "a" in front of "manifest:

for example (at minimum) we might instead display:
```
WARNING: using the key 'package' inside of **a manifest file may be deprecated**, please use the key 'packages' instead.
```
This helps the user understand these are "keys" in the specification grammar.

**Comment by mrutkows** [comment]
Ideally, I would like to add coloration of our output to highlight success/warning/failure messages...

**Comment by pritidesai** [comment]
Warnings are displayed in yellow, info messages displayed in blue, and error message are displayed in red.
