### ISSUE TITLE
whiskclient insecure

### ISSUE THREAD

**Issue by beemarie** [apache/incubator-openwhisk-wskdeploy#560]
We're planning to use this in production, and should be using secure connections, not ignoring certificate signing.  Can we pass this as an option to wskdeploy instead?

See:
    clientConfig = &whisk.Config{
...
        **Insecure:  true, // true if you want to ignore certificate signing**
    }

**Comment by houshengbo** [comment]
I think we can make it configurable by a flag of wskdeploy command.

**Comment by mrutkows** [comment]
@houshengbo agree to use a flag (default off would be my preference)... would like to discuss as well understanding that IMO this should be a property we pick up in .wskprops and the user sets on/off so they do not have to use a flag every time.  Of course, we should provide feedback to the user that we are secure/insecure at the same point we tell them where we get their keys from.

**Comment by pritidesai** [comment]
An alternative to command line argument (--insecure) would be reading it from the manifest file.
