### ISSUE TITLE
Do not display wskdeploy flags/help on YAML parsing or REST API (Failures) errors

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#569]
If the user correctly supplied the command line command and arguments (flags),  and 

1) there is an error parsing either manifest or deployment files <or>
2) there is an error during deployment (using HTTP REST APIs), 

**Please do not show the user the Cobra "--help" instructions.**  

Here is what I saw on a failed REST call (but parameters were correct).

```
(*ServiceDeployer).Deploy]:242:[Err] Deployment did not complete sucessfully. Run `wskdeploy undeploy` to remove partially deployed assets.
Error: /Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/servicedeployer.go [623]: OpenWhisk Client Error =====> The connection failed, or timed out. (HTTP status code 502) Error code: 246.

Usage:
  wskdeploy [flags]
  wskdeploy [command]

Available Commands:
  add         Add an action, feed, trigger or rule to the manifest
  help        Help about any command
  init        Init helps you create a manifest file on OpenWhisk
  publish     Publish a package to a registry
  report      Returns summary of what's been deployed on OpenWhisk in specific namespace
  undeploy    Undeploy assets from OpenWhisk
  version     Print the version number of openwhisk-wskdeploy

Flags:
  -a, --allow-defaults       allow defaults
  -i, --allow-interactive    allow interactive prompts
      --apihost string       whisk API HOST
      --apiversion VERSION   whisk API VERSION
  -u, --auth KEY             authorization KEY
      --config string        config file (default is $HOME/.wskprops)
  -d, --deployment string    path to deployment file
  -h, --help                 help for wskdeploy
  -m, --manifest string      path to manifest file
  -n, --namespace string     namespace
  -p, --pathpath string      path to serverless project (default ".")
  -s, --strict               allow user defined runtime version
  -t, --toggle               Help message for toggle
  -v, --verbose              verbose output

Use "wskdeploy [command] --help" for more information about a command.

Error: /Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/servicedeployer.go [623]: OpenWhisk Client Error =====> The connection failed, or timed out. (HTTP status code 502) Error code: 246.
```
Because changing any of the flags will NOT help.

Also, if '-v' (verbose) is NOT set you may want to provide an INFORMATIONAL message to tell the user to turn it on to see more detailed error information.

**Comment by pritidesai** [comment]
yup I agree, its little annoying and becomes difficult to spot the error message produced by 'wskdeploy' in case of failure.

**Comment by houshengbo** [comment]
@mrutkows @pritidesai I strongly suspect that the usage, available commands and flags are printed by cobra library automatically, if there is any error raised. We did not programmatically and actively print them.

We have to dig into the way to turn them off in cobra IMO.

**Comment by pritidesai** [comment]
@houshengbo Command struct has few flags which we can set to silence usage and printing error twice.

Silence usage: https://github.com/spf13/cobra/blob/master/command.go#L111
Quiet errors: https://github.com/spf13/cobra/blob/master/command.go#L108
