### ISSUE TITLE
Colorize Success/Warning/Failure/Status outputs

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#577]
Many of our command line utilities add packages that "colorize" certain meaningful strings such as:

1) Success messages - encode the words "ok", "success". etc. in a green color
2) Warning messages - encode the words "warning" in a yellow color
3) Error messages - encode the words "error" in red color.
4) status messages - some (not all informational messages) could be encoded in a cyan (bright blue) color. these are messages the print status or summary information (that display some intermediate or final conclusions or metrics)

**Comment by mrutkows** [comment]
In python, for example I have used packages the help with this...  or you can encode the console-specific (unix/linux compatible) character codes around strings:

See: https://github.com/apache/incubator-openwhisk-utilities/blob/master/scancode/scanCode.py

**Comment by pritidesai** [comment]
This is fixed with @mrutkows recent effort on error reporting overhaul.
