### ISSUE TITLE
Remove "report" command as it is not a "wskdeploy" concept

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#586]
Early on, this command may have had value to the developer of the wskdeploy utility, but this function (if not tied to a Manifest file) is just a shortcut for what the user could do with the normal CLI ('wsk' command).

We agreed to take forward the idea of instead a 'verify' command that would create a report relative to a manifest (and perhaps a deployment) file in this issue: https://github.com/apache/incubator-openwhisk-wskdeploy/issues/582

**Comment by pritidesai** [comment]
We have a list of enhancements requested to add support for `report` functionality. See Epic (issue #761)
