### ISSUE TITLE
On tagged releases of wskdeploy, publish new docker image to openwhisk/wskdeploy

### ISSUE THREAD

**Issue by beemarie** [apache/incubator-openwhisk-wskdeploy#597]
This supports the work being done to make wskdeploy available in /whisk.system/ catalog.

**Comment by beemarie** [comment]
This can be closed, but I don't see my invite for access.  Can you resend it @mrutkows ?

**Comment by houshengbo** [comment]
This issue is fixed by https://github.com/apache/incubator-openwhisk-wskdeploy/pull/596.
