### ISSUE TITLE
Support "raw-http" field on Action

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#615]
Please add support for this (new) field (i.e., "raw-http") as an explicit field (with dedicated unit tests) within yamlparser.go.

Although we have some code that attempts to define raw-http as an annotation in misc.go:
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/utils/misc.go
```
//for web action support, code from wsk cli with tiny adjustments
const WEB_EXPORT_ANNOT = "web-export"
const RAW_HTTP_ANNOT = "raw-http"
const FINAL_ANNOT = "final"

func WebAction(webMode string, annotations whisk.KeyValueArr, entityName string, fetch bool) (whisk.KeyValueArr, error) {
	switch strings.ToLower(webMode) {
	case "yes":
		fallthrough
	case "true":
		return webActionAnnotations(fetch, annotations, entityName, addWebAnnotations)
	case "no":
		fallthrough
	case "false":
		return webActionAnnotations(fetch, annotations, entityName, deleteWebAnnotations)
	case "raw":
		return webActionAnnotations(fetch, annotations, entityName, addRawAnnotations)
	default:
		return nil, errors.New(webMode)
	}
}
```

there was even a unit test that attempted to test it within an annotation, but was the test did NOT actually work (i.e., the in-line unit test never added "raw-http' as an annotations or else it would have failed at the time since annotations on actions were broken).
```
func TestComposeActionsForWebActions(t *testing.T) {
    data :=
        `package:
  name: helloworld
  actions:
    hello:
      function: ../tests/src/integration/helloworld/actions/hello.js
      web-export: true`
    dir, _ := os.Getwd()
```

There is NO way for a user to actually set it as an option in the YAML (now in spec. 0.9.0)

See the docs for details:
https://console.bluemix.net/docs/openwhisk/openwhisk_webactions.html#raw-http-handling

**Comment by pritidesai** [comment]
Fixed with PR #707
