### ISSUE TITLE
WIP: Support "project" as a synonym for "application"

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#617]
As we move wskdeploy more towards supporting higher order "project" build/integration pipelines we need to move away from the term "application" which was arbitrarily selected earlier on in the specification design.

Mark "application" as deprecated, support "project"

**Comment by mrutkows** [comment]
See related issue: https://github.com/apache/incubator-openwhisk-wskdeploy/issues/618 for discussion which may impact the coding of this feature.

**Comment by pritidesai** [comment]
Can not update title to indicate Priti working on it ...
