### ISSUE TITLE
Support "blackbox" Docker images

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#623]
This has been a discussion since last Sept. and asked Daisy to look into supporting at that time.  Need to track this work via this issue.

```
Sept 2016:
Daisy: Blackbox (Docker) Actions: Need to think about how to set the field "runtime" if it is a docker action. We should document it.
```

**Comment by mrutkows** [comment]
See: https://github.com/apache/incubator-openwhisk-wskdeploy/issues/279

**Comment by mrutkows** [comment]
TODO: look at CLI conventions for what they call this?  I believe its "docker" so we would then use:
runtime: docker

then we would have to be able to validate the image is valid and if we need to add it to an existing key or new key in the YAML manifest.  Need a recommendation here on what is clear/friendly to the user.

**Comment by pritidesai** [comment]
Private docker repos are not yet supported by openwhisk, see https://github.com/apache/incubator-openwhisk/issues/1362
