### ISSUE TITLE
Refactor Whisk Deploy errors into new package to avoid cyclic dependencies

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#650]
currently, wskdeployerror.go (and it unit test file) are in "utils" package; however, if we want to do better unit testing we need to be able to test errors against manifests and the YAML parser.  This would mean importing "parsers" into "utils" which leads to cyclic dependency errors in GoLang.

To overcome this cyclic error, we must refactor the error modules into a new "wskdeplyerror" package.

**Comment by pritidesai** [comment]
Fixed with `wskderrors` at https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/wskderrors/wskdeployerror.go
