### ISSUE TITLE
whiskclient_test.go: "TestNewWhiskConfigInteractiveMode" incomplete/commented out

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#693]
Either code the test (if valid/applicable/unique) or remove the commented out code.

**Comment by pritidesai** [comment]
priority low **enhancements**

Introducing interactive mode through go unit tests is not trivial, if we can add interactive mode, we should add tests across the whole wskdeploy in interactive mode. [To be determined]
