### ISSUE TITLE
Deprecate "Application" keyword (in favor of Project)

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#696]
At some point, we need to fully deprecate/remove support for the "Application" kwyword.  THis will involve:

- Removing functional code that accepts "Application" in yaml parser/schema
- replacing "Warning" messages with errors
- updating all unit tests that use "Application"
- updating all integration tests that use "Application"
- verifying any manifests/templates outside our project are duly notified (via Apache "dev" list)

**Comment by pritidesai** [comment]
Once we decide when its time, deprecating Application keyword is made easier with:

https://github.com/apache/incubator-openwhisk-wskdeploy/pull/627

Start by deleting this struct member: https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/yamlparser.go#L223

I would categorized as **clean-up**

**Comment by mrutkows** [comment]
@pritidesai elevating to "high" so that we get all the deprecated schema out of the next build.
