### ISSUE TITLE
Unable to specify Raw HTTP

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk-wskdeploy#704]
I have an Web Action `web-export: true` but cannot set it to use Raw HTTP. Looking through the code thought `raw-http: true` would do the trick but it did not...

**Comment by pritidesai** [comment]
Hi @ScottChapman we have an enhancement opened here #615 sometime back, `wskdeploy` does not yet support explicit setting `raw-http`, working on it to add it.

**Comment by ScottChapman** [comment]
how often are new builds produced? Ones in the releases folder seem kind old(ish)
