### ISSUE TITLE
Action: Web (action): Support alias key "web" in addition to "web-export"

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#713]
See: https://github.com/apache/incubator-openwhisk/blob/master/docs/annotations.md

This allows wskdeploy to match the CLI and offer a "simpler" name.

**Comment by pritidesai** [comment]
This enhancement needs an additional member in `Action` struct at https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/yamlparser.go#L106. Define `web` in addition to `web-export` with:

```
Web  string  `yaml:"web"`
```

Define a new function `getWeb()` similar to `getProject()` at https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/parsers/yamlparser.go#L228.

Replace all the occurrences of `Action.Webexport` with `Action.getWeb()`
