### ISSUE TITLE
Enable query of dynamic runtimes from deployment host

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#734]
This API /endpoint should be working again... we should retry the query and if fails fall back on hardcoded list of runtimes.

**Comment by pritidesai** [comment]
@mrutkows We do have support for reading runtimes dynamically from openwhisk endpoint, PR #737 is adding info messages saying where the runtimes are coming from.

With PR #737, wskdeploy produces info when the openwhisk endpoint is not reachable:
```
Info: Unmarshal OpenWhisk runtimes from local values.
```

and when its reading runtimes dynamically:

```
Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
```

**Comment by mrutkows** [comment]
@pritidesai thanks. this was opened as it came up on Slack regarding upgrade of Python runtime version and did not immediately have time to check the code.  Also, glad we have an issue for an info. message.
