### ISSUE TITLE
ReadProjectDirectory() does not appear to work; uses default package

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#748]
filesystemreader.go has the function ReadProjectDirectory() which has code that creates actions it finds under the "default" (or root package) which is not a concept we support.  We need to take a serious look at this code and the code that invokes it and make it work properly.

```
ReadProjectDirectory

```

**Comment by pritidesai** [comment]
`ReadProjectDirectory()` is called when `wskdeploy` is invoked with `--use-defaults`. Lets delete this function and other functions from `filesystemreader.go`. This functionality was added to support auto creation of manifest file based on the directory structure `actions/<actionname>/...` in interactive mode. After discussing with @mrutkows regarding deprecating interactive mode, `--use-defaults` can be deprecated as well.
