### ISSUE TITLE
Deprecate interactive mode in wskdeploy

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#758]
We started Whisk Deploy with interactive mode a year back but now, we have come long way from prototyping mode to running in production. As of now, we have no use case for Interactive mode, so from code maintenance perspective, we have decided to deprecate and remove support for interactive mode from Whisk Deploy.

**Comment by csantanapr** [comment]
+1

**Comment by mrutkows** [comment]
@csantanapr already gutted 90% of this... the only part left is "report" which we plan to perhaps preserve as part of a "verify" step

**Comment by mrutkows** [comment]
@pritidesai we will preserve the interactive flag as a means to stop/verify assets before deployment

**Comment by pritidesai** [comment]
sure @mrutkows we can, in that case, we should rename `--allow-interactive` and `-i` to `--report`. Also, there are some code paths we need to delete specially in `whiskclient`:

```
grep -r "interactive" .
./deployers/whiskclient.go:// (5) prompt for values in interactive mode if any of them are missing
./deployers/whiskclient.go:     // If we still can not find the values we need, check if it is interactive mode.
./deployers/whiskclient_test.go:        assert.Nil(t, err, "Failed to read credentials in interactive mode")
./parsers/manifest_parser.go:                   // TODO() interactive ask for branch, AND consider YAML specification to allow key for branch
...
```
