### ISSUE TITLE
wskdeploy only supports /whisk.system bindings or github.com packages

### ISSUE THREAD

**Issue by ddragosd** [apache/incubator-openwhisk-wskdeploy#762]
In my case I'm dealing with 2 different namespaces, and I'd like to setup a package binding between these 2 namespaces. Is there any reason why only `whisk.system` and `github` are supported right now ?

**Comment by mrutkows** [comment]
@ddragosd no, we thought github was a first step towards a distributed package ecosystem. Do you have an example we can use as a functional test?

**Comment by mrutkows** [comment]
from Dragos via Slack:
```
a use-case would be one developer that creates a shared package in a namespace other than `whisk.system`
```

**Comment by ddragosd** [comment]
Sure, 
A developer having `namespaceA` creates a shared package: 

```
wsk package create public --shared yes
```

The another developer having `namespaceB` wants to create a package binding:

```
wsk package bind /namespaceA/public my-package --param X Y
```

**Comment by mrutkows** [comment]
So this is the dependency support...

**Comment by mrutkows** [comment]
Effectively, wherever we are using this function in dependencies.go:
```

func LocationIsBinding(location string) bool {
	if strings.HasPrefix(location, "/whisk.system") || strings.HasPrefix(location, "whisk.system") {
		return true
	}

	return false
}
```
to test for binding is restricting namespace bindings which we should not do.  We should assume any namespace binding is "public" unless we get an error from the CLI.

**Comment by ddragosd** [comment]
🎉  💯 
many thanks !
