### ISSUE TITLE
wskdeploy does not display version using "version" command

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#767]
The injection of a version would have to be done as part of the build process.

currently here is what you see:
```
$ ./wskdeploy version
wskdeploy build-version: unset--unset
```

**Comment by tz70s** [comment]
Hi, the version of wskdeploy is currently depends on ldflags for injection in _some_ places (`Makefile`, `build.sh`).

IMHO, it would be nice if we unified the building process, i.e. `make`. Therefore, the build can be always inject the build version via ldflags without adding from developers.

However, seems like there are still some problems in unit tests after quickly look around, in which the `make build` depends on `test`.
