### ISSUE TITLE
consider renaming _OW_** annotations

### ISSUE THREAD

**Issue by lionelvillard** [apache/incubator-openwhisk-wskdeploy#778]
the convention is to use the camel case convention: https://github.com/apache/incubator-openwhisk/blob/master/docs/annotations.md

**Comment by pritidesai** [comment]
@lionelvillard please suggest renaming:

- `__OW_FILE` to `__OW_File`
- `__OW_PROJECT_HASH` to `__OW_Project_Hash`
- `__OW_PROJECT_Name` to `__OW_Project_Name`

or

- `__OW_FILE` to `OWFile`
- `__OW_PROJECT_HASH` to `OWProjectHash`
- `__OW_PROJECT_Name` to `OWProjectName`

or 

- `__OW_FILE` to `OpenWhiskFile`
- `__OW_PROJECT_HASH` to `OpenWhiskProjectHash`
- `__OW_PROJECT_Name` to `OpenWhiskProjectName`

**Comment by lionelvillard** [comment]
I would suggest:
* `__OW_FILE` to `file`. Should be relative to the manifest (if any). The shell already uses `file` (top-level annotation)
* `__OW_PROJECT_NAME` to `projectName`. 
* `__OW_PROJECT_HASH` to `projectHash` or `manifestHash`. 

Note that only `projectHash` is specific to how `wskdeploy` implements deleting assets removed from the manifest thus the suggestion to instead name it `manifestHash`.

**Comment by mdeuser** [comment]
this would be a breaking change to existing actions.  is the propose to create these as additional variables as opposed to replacements?
