### ISSUE TITLE
Rename --managed to --sync

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#780]
@csantanapr suggested a while back we rename `--managed` flag to `--sync`, sorry @csantanapr I haven't been able to address this yet. But before its too late and since other teams have started using managed project, lets introduce this new flag `--sync` first and overload it with `--managed`. After checking with all impacted teams and making sure they have migrated to using `--sync`, deprecate `--managed` flag.

**Comment by csantanapr** [comment]
Sounds good to me and doc the —sync and doc —manage is deprecated but both work for a while
