### ISSUE TITLE
Crash when running with __OW_API_KEY and __OW_API_HOST set

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk-wskdeploy#791]
I set those env vars to be able to run/debug actions locally and they appear to crash wskdeploy:

> SECMacbookPro:Dumper scottchapman$ wskdeploy
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/apache/incubator-openwhisk-wskdeploy/cmd.substCmdArgs(0x149c77c, 0x1a)
> 	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:86 +0x3d6
> github.com/apache/incubator-openwhisk-wskdeploy/cmd.Execute()
> 	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:61 +0xdb
> main.main()
> 	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/main.go:26 +0x20
>

**Comment by pritidesai** [comment]
[This](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/cmd/root.go#L103) particular check is causing this failure:

```
func init() {
	// TODO() move Env var. to some global const
	utils.Flags.WithinOpenWhisk = len(os.Getenv("__OW_API_HOST")) > 0
```

Assumption here is when this kind of env. variable is set, its considered as `wskdeploy` is running as OpenWhisk action. @lionelvillard @beemarie do you know if we have this kind of use case? This particular path seems broken.

**Comment by lionelvillard** [comment]
I don't think we have this use case anymore (ie. run wskdeploy as a go action).

**Comment by ScottChapman** [comment]
I use those env vars in order to run actions locally for debugging. I will be running my actions in node using the openwhisk module, and specifying API & KEY for my Cloud Functions space.

So currently I need to unset those two in order to deploy.

Perhaps there should be an explicit trigger for that instead of implicit based on other variables that user used for other things as well?

**Comment by csantanapr** [comment]
Bump

**Comment by beemarie** [comment]
@pritidesai & I discussed offline.  incubator-openwhisk-package-deploy uses exec command to call wskdeploy.  This should not result in wskdeploy being called as an openwhisk action.  Priti is going to quickly look over package-deploy to confirm before deprecating.

**Comment by ScottChapman** [comment]
Just to be clear, I am running code locally which uses the nodejs client NPM module. It leverages the API & KEY variables to be able to connect to the OW I am testing against.

wskdeploy just shouldn't crash if I am running it locally with those set.

**Comment by ScottChapman** [comment]
I'm not entirely clear on where this gets set:
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/c08d8053dec6fb478702e662f89d5bdb5cea8741/utils/flags.go#L26
But it appears it is getting set when it detects that both HOST & KEY are set. Just not sure how that is getting set...

**Comment by pritidesai** [comment]
Thanks @beemarie, I have verified that package deploy is not invoking `wskdeploy` as an OpenWhisk action and it is safe to deprecate this code path. 

@ScottChapman, [here](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/cmd/root.go#L103) in `init()` function, `WithinOpenWhisk` is getting set depending on whether env. variable `__OW_API_HOST` is set or not. This was introduced when `wsksdeploy` was just a concept and could be run as an action like:

```
wsk action create wskdeploy <wskdeploy source or binary>
wsk action invoke wskdeploy --param ....
```

This code path hasn't been tested or maintained during the development cycle and since its not used anywhere, its safe to deprecate and delete flag `WithinOpenWhisk`.

**Comment by pritidesai** [comment]
So once this issue is fixed, `wskdeploy` wouldn't crash when you are running locally with these env. variables (__OW*) set.

**Comment by mrutkows** [comment]
@pritidesai it seems that package-deploy does not use them, but did ask for Belinda to affirm herself that this detection of JSON parms is no longer needed.
