### ISSUE TITLE
wskdeploy assumed "guest" namespace if one is not set

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-wskdeploy#810]
if you have a .wskprops file without a NAMESPACE defined, it appears wskdeploy assumes "guest" as the namespace which is incorrect. It should use "_" or do an actual look up and retrieve the namespace.

```
> wskdeploy export
Info: The API host is [https://openwhisk.ng.bluemix.net], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [guest], from .wskprops.
Info: Unmarshal OpenWhisk runtimes from local values.
Error: The supplied authentication is not authorized to access 'guest'. (code 2898491)
```

**Comment by pritidesai** [comment]
Default namespace "guest" is coming from [Go Client](https://github.com/apache/incubator-openwhisk-client-go/blob/master/whisk/wskprops.go#L41). Changing in Go Client.

**Comment by mrutkows** [comment]
@rabbah yes, it is in Go client, we make not assumptions in wskdeploy; however, at one point we copied the code from Go client (no longer) and still have a legacy comment that we default to guest (perhaps the "we" is collectively including the known behavior from Go client):

grep -rn "guest" . 
```
./wski18n/resources/en_US.all.json:236:    "translation": "\nPlease provide a namespace [default value is guest]: "
./deployers/whiskclient_test.go:46:	WSKPROPS_NAMESPACE = "guest"
./parsers/manifest_parser.go:248:	//The namespace for this package is absent, so we use default guest here.
./parsers/manifest_parser.go:968: *			"namespace":"guest",
```

@pritidesai  We do need to remove the translated string that indicates we default to guest as well.
