### ISSUE TITLE
wsk deploy not picking up new target

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk-wskdeploy#819]
This has actually happened to me a couple of times. I will be working in a space, wskdeploy working fine. Then I change the target with `bx target -s <different space>`, do a deploy, and it deploys to the old space. See this as an example:

> SECMacbookPro:Weather scottchapman$ wskdeploy
> Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
> Info: The auth key is set, from .wskprops.
> Info: The namespace is [_], from .wskprops.
> Info: The apigw access token is set, from .wskprops.
> Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
> Warning: The mandatory key [package version] should be set. Using default value [0.0.1]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Warning: The mandatory key [package license] should be set. Using default value [unlicensed]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Info: Deploying package [Forcast] ...
> Info: package [Forcast] has been successfully deployed.
> 
> Info: Deploying action [Forcast/WeatherForcast] ...
> Info: action [Forcast/WeatherForcast] has been successfully deployed.
> 
> Info: Deploying action [Forcast/ForcastSequence] ...
> Info: action [Forcast/ForcastSequence] has been successfully deployed.
> 
> Info: Deploying rule [WeatherRule] ...
> Info: rule [WeatherRule] has been successfully deployed.
> 
> Success: Deployment completed successfully.
> SECMacbookPro:Weather scottchapman$ bx wsk list
> Entities in namespace: default
> packages
> actions
> triggers
> rules
> SECMacbookPro:Weather scottchapman$ bx target
> 
>                      
> API endpoint:     https://api.ng.bluemix.net (API version: 2.92.0)   
> Region:           us-south   
> User:             scottchapman@us.ibm.com   
> Account:          Scott Chapman's Account (5f9ee7865987611d27bd95c03e4b0ced)   
> Resource group:   default   
> Org:              scottchapman@us.ibm.com   
> Space:            Weather   
> SECMacbookPro:Weather scottchapman$ env | grep OW
> 

I did check and and the artifacts were created in the other space...

**Comment by ScottChapman** [comment]
And then it magically worked... Here is the entire transcript:

> SECMacbookPro:Weather scottchapman$ wskdeploy
> Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
> Info: The auth key is set, from .wskprops.
> Info: The namespace is [_], from .wskprops.
> Info: The apigw access token is set, from .wskprops.
> Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
> Warning: The mandatory key [package version] should be set. Using default value [0.0.1]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Warning: The mandatory key [package license] should be set. Using default value [unlicensed]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Info: Deploying package [Forcast] ...
> Info: package [Forcast] has been successfully deployed.
> 
> Info: Deploying action [Forcast/WeatherForcast] ...
> Info: action [Forcast/WeatherForcast] has been successfully deployed.
> 
> Info: Deploying action [Forcast/ForcastSequence] ...
> Info: action [Forcast/ForcastSequence] has been successfully deployed.
> 
> Info: Deploying rule [WeatherRule] ...
> Info: rule [WeatherRule] has been successfully deployed.
> 
> Success: Deployment completed successfully.
> SECMacbookPro:Weather scottchapman$ bx wsk list
> Entities in namespace: default
> packages
> actions
> triggers
> rules
> SECMacbookPro:Weather scottchapman$ bx target
> 
>                      
> API endpoint:     https://api.ng.bluemix.net (API version: 2.92.0)   
> Region:           us-south   
> User:             scottchapman@us.ibm.com   
> Account:          Scott Chapman's Account (5f9ee7865987611d27bd95c03e4b0ced)   
> Resource group:   default   
> Org:              scottchapman@us.ibm.com   
> Space:            Weather   
> SECMacbookPro:Weather scottchapman$ env | grep OW
> SECMacbookPro:Weather scottchapman$ wskdeploy undeploy
> Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
> Info: The auth key is set, from .wskprops.
> Info: The namespace is [_], from .wskprops.
> Info: The apigw access token is set, from .wskprops.
> Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
> Warning: The mandatory key [package version] should be set. Using default value [0.0.1]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Warning: The mandatory key [package license] should be set. Using default value [unlicensed]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Info: Undeploying rule [WeatherRule]...
> Error: Undeployment did not complete sucessfully.
> Error: servicedeployer.go [1580]: [ERROR_WHISK_CLIENT_ERROR]: Error code: 148: The requested resource does not exist. (code 9821971): HTTP Response Status: 404 Not Found HTTP Response Body: {"error":"The requested resource does not exist.","code":9821971}
> SECMacbookPro:Weather scottchapman$ wskdeploy
> Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
> Info: The auth key is set, from .wskprops.
> Info: The namespace is [_], from .wskprops.
> Info: The apigw access token is set, from .wskprops.
> Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
> Warning: The mandatory key [package version] should be set. Using default value [0.0.1]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Warning: The mandatory key [package license] should be set. Using default value [unlicensed]...
> Warning: The value for key [package version] is not saved in the current version of wskdeploy.
> Info: Deploying package [Forcast] ...
> Info: package [Forcast] has been successfully deployed.
> 
> Info: Deploying action [Forcast/WeatherForcast] ...
> Info: action [Forcast/WeatherForcast] has been successfully deployed.
> 
> Info: Deploying action [Forcast/ForcastSequence] ...
> Error: Deployment did not complete sucessfully. Run `wskdeploy undeploy` to remove partially deployed assets.
> Error: servicedeployer.go [1580]: [ERROR_WHISK_CLIENT_ERROR]: Error code: 148: The requested resource does not exist. (code 9822263): HTTP Response Status: 404 Not Found HTTP Response Body: {"error":"The requested resource does not exist.","code":9822263}
> SECMacbookPro:Weather scottchapman$ bx wsk list
> Entities in namespace: default
> packages
> /scottchapman@us.ibm.com_Weather/Forcast                               private
> /scottchapman@us.ibm.com_Weather/Bluemix_WeatherCompany_Credentials    private
> actions
> /scottchapman@us.ibm.com_Weather/Forcast/WeatherForcast                private nodejs:8
> triggers
> rules

**Comment by pritidesai** [comment]
Hi @ScottChapman can you please check what was the namespace in `.wskprops` after you run `bx target -s <different space>`?  `wskdeploy` picks up namespace from `.wskprops`, may be `.wskprops` was not updated.

**Comment by ScottChapman** [comment]
@pritidesai - yea, I think what was going on was that the `bx target ...` command was not updating the .wskproperties. I had to run a `bx wsk ...` command for that to happen. I understand what's going on now, so I can deal with it until `deploy` becomes a command of `bx`. Thanks!

**Comment by pritidesai** [comment]
thanks @ScottChapman
