### ISSUE TITLE
Document export functionality

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#839]
@kpavel can you please add a doc on export functionality under https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/docs

Please describe the details such as:

1. What does it do? How its useful?
1. `wskdeploy` command line for export functionality
2. Sample manifest files exported using this functionality.

**Comment by davidbreitgand** [comment]
@pritidesai @kpavel : I added the documentation:
https://github.com/apache/incubator-openwhisk-wskdeploy/pull/862/files
