### ISSUE TITLE
wskdeploy version gives unset--latest

### ISSUE THREAD

**Issue by brunogirin** [apache/incubator-openwhisk-wskdeploy#855]
When I run `wskdeploy version`, I get a reply that doesn't help identify the actual version in use. This is the output when using the `latest` release as of this morning (2018-04-05), which should be 0.9.2 as far as I know:

```
$ wskdeploy version
wskdeploy build-version: unset--latest
```

**Comment by mrutkows** [comment]
yes, we know... https://github.com/apache/incubator-openwhisk-wskdeploy/issues/767

**Comment by brunogirin** [comment]
Ah sorry, I failed to check properly.
