### ISSUE TITLE
Change all manifest.yaml and deployment.yaml files to use Mini ASF license header

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#889]
I agree with Carlos' comment in PR [#709](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/709) that full headers in all the YAML manifest (and deployment) files is too much.

Carlos' comment from PR [#709](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/709):
```
I really don’t like the examples manifest yaml files in tests/usecases/ currently 
being used as test fixtures and have the header it really no very good to have 
this extra 16 lines on this examples they can be used as

This files should be ignore from rat and this is allowed this are none signifancg (sic)
creative content.

The creative content is located in the source code for the golang wskdeploy application
```

As test files, they should all be changed to mini-header.

**Comment by daisy-ycguo** [comment]
https://github.com/apache/incubator-openwhisk-wskdeploy/pull/914 is merged. We can close this issue.
