### ISSUE TITLE
wskdeploy export doesn't support multiple packages in a single project

### ISSUE THREAD

**Issue by brunogirin** [apache/incubator-openwhisk-wskdeploy#898]
When running `wskdeploy` on a project that contains multiple packages, I get the following message:

```
Error: currently can't work with more than one package managed by one project
```

This is using the `latest` version of `wskdeploy` downloaded on Thursday 10th May, around 15:00 GMT. When I comment out all but one of the packages, run `wskdeploy sync` followed by `wskdeploy export`, it all works fine.

## Steps to reproduce:

1. Create a manifest with a project that includes 2 packages
2. Run `wskdeploy sync`: all works well and all actions are deployed
3. Run `wskdeploy export`: it fails with the error message above; when doing this, it downloads the artefacts for the first package and fails to write any manifest

## Expected outcome

The tool should be able to handle multiple packages.

**Comment by pritidesai** [comment]
@kpavel can you please add support for multiple packages while exporting ow entities?

**Comment by pritidesai** [comment]
again, @kpavel has fixed it, let me know if you run into any issues.

**Comment by pritidesai** [comment]
Closing this as its fixed now.
