### ISSUE TITLE
Error when invoke a zip action created with wskdeploy

### ISSUE THREAD

**Issue by Nickkr** [apache/incubator-openwhisk-wskdeploy#913]
I tried to follow the example on how to deploy zip-actions with wskdeploy from [https://medium.com/openwhisk/whisk-deploy-zip-actions-abcc8c01ac4](``).

When i tried to invoke the action with the bluemix cli I received following error: "Initialization has failed due to: There was an error uncompressing the action archive."

I pulled the action from bluemix in order to look at the zip file with following command:
"bx wsk action get zipaction/my-zip-action --save

I found out, that it did not only zip the my-zip-action folder it ziped the absolute path starting from the c: drive

![zipaction](https://user-images.githubusercontent.com/18218692/40257001-c8bf5280-5aec-11e8-8546-774862fb0112.png)

**Comment by EternalPhane** [comment]
@Nickkr I'm having a similar issue except that the zipped path starts from the folder contains manifest. Did you ever find the resolution?

**Comment by Nickkr** [comment]
@EternalPhane No, never got it to work on Windows. Working fine for me on Linux though.
