### ISSUE TITLE
binary releases for a platform include binaries for all other platforms

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-wskdeploy#924]
```
> unzip openwhisk_wskdeploy-latest-mac-amd64.zip
> ls openwhisk_wskdeploy-latest-mac-amd64
LICENSE.txt                         docs                                wskdeploy-0.9.3.1-linux-amd64.tgz   wskdeploy-0.9.3.1-windows-386.zip
NOTICE.txt                          wskdeploy                           wskdeploy-0.9.3.1-mac-386.zip       wskdeploy-0.9.3.1-windows-amd64.zip
README.md                           wskdeploy-0.9.3.1-linux-386.tgz     wskdeploy-0.9.3.1-mac-amd64.zip

**Comment by rabbah** [comment]
<img width="594" alt="screen shot 2018-05-23 at 5 30 02 pm" src="https://user-images.githubusercontent.com/4959922/40452180-f50f1f6c-5eae-11e8-8cce-9c5c61f36919.png">

checked another and it's also bloated with other binaries --- is this intentional?

**Comment by rabbah** [comment]
worse, the binary is the wrong format:

```
file wskdeploy
wskdeploy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, with debug_info, not stripped
```

considering this a bug.

**Comment by houshengbo** [comment]
@rabbah It is a mistake to add the additional tgz and zip files inside this artifact, which causes its size to become incredibly large.
I fixed it with the PR: https://github.com/apache/incubator-openwhisk-wskdeploy/pull/934.

Regarding the format of the binary, what should be the correct format?

**Comment by rabbah** [comment]
I downloaded the Mac release but the binary is for Linux.
