### ISSUE TITLE
hardcoded protocol does not allow for http to be used

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-wskdeploy#928]
this line hardcodes `https` as the protocol.

https://github.com/apache/incubator-openwhisk-wskdeploy/blob/b9fd4d317888319ddd3fea3ad8458b2b661ec407/utils/runtimes.go#L85

if the api host already includes a protocol, wskdeploy fetches the runtime manifest from hardcoded values here:
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/b9fd4d317888319ddd3fea3ad8458b2b661ec407/utils/runtimes.go#L229

this is startling - instead `wskdeploy` should fail --- the hardcoded values could be very different from the deployment wrt action default, supported actions, etc... isn't this dangerous?!

**Comment by pritidesai** [comment]
This can be disabled using `--strict` flag. 

```
./wskdeploy -m tests/dat/manifest_validate_action_all.yaml --strict
Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [_], from .wskprops.
Info: The apigw access token is set, from .wskprops.
Error: runtimes.go [116]: [ERROR_RUNTIME_ERROR]: Failed to retrieve runtimes Get https://openwhisk.ng.bluemix.net: dial tcp: lookup openwhisk.ng.bluemix.net: no such host.
```
