### ISSUE TITLE
if manifest read fails, wskdeploy should not read details from hardcoded manifest

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-wskdeploy#929]
wskdeploy fetches the runtime manifest from hardcoded values here should it fail reading from the API host.

https://github.com/apache/incubator-openwhisk-wskdeploy/blob/b9fd4d317888319ddd3fea3ad8458b2b661ec407/utils/runtimes.go#L229

this is startling - instead `wskdeploy` should fail --- the hardcoded values could be very different from the deployment wrt action default, supported actions, etc... isn't this dangerous?!

**Comment by pritidesai** [comment]
Reading hardcoded values can be disabled using `--strict` flag.
