### ISSUE TITLE
Add sample manifests for existing packages and support it.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#94]
Now the use cases contains sample ones, we need support real and more complex openwhisk packages use cases such as https://github.com/openwhisk/openwhisk-package-rss
Github feed advanced, polygen tracking etc mentioned in the specification.

**Comment by daisy-ycguo** [comment]
@lzbj I suggest we separate this issue into small issues, e.g.
- support RSS pkg
- support openwhisk-catalog 
- support OWGitSlackBot

Then it will be easier to manage.
By the way, I'm think about proposing PR with manifest and deployment files to each repo if the use case has its own repo. For example, we can provide a PR to openwhisk-package-rss repo to add manifest.yml and deployment.yml other than moving the source code of openwhisk-package-rss to our repo.

Or maybe we add a sample folder and add all manifest and deployment there and link to the source code of each use case repo.

**Comment by lzbj** [comment]
@daisy-ycguo, please open new issues if you think we'd better do, we can discuss with others later.

**Comment by paulcastro** [comment]
Do we need to add both deployment and manifest files? I think we just need to add a manifest file to the repos.  In our current model, the deployment file is just used for deployment instances.

**Comment by lzbj** [comment]
@daisy-ycguo @pritidesai  please open issues if you need to add more real word app usecases, as we already have a lot of test cases, so I'll close this one.

**Comment by pritidesai** [comment]
Lets discuss this in today's scrum meeting and than open issues accordingly.
