### ISSUE TITLE
API section doesn't support response-type

### ISSUE THREAD

**Issue by brunogirin** [apache/incubator-openwhisk-wskdeploy#944]
According to the [API Gateway documentation](https://github.com/apache/incubator-openwhisk/blob/master/docs/apigateway.md), in order to have full control over the HTTP response, it is necessary to specify `--response-type http` when creating an API with `wsk`. The current `wskdeploy` manifest doesn't allow that parameter to be specified in the `api` section.

## Expected behaviour

It should be possible to specify `response-type: http` in the manifest and create the corresponding API accordingly.

## Related issues

This issue is related to #940 .

**Comment by pritidesai** [comment]
@brunogirin I am tracking this with issue #724

**Comment by brunogirin** [comment]
Sorry for the duplicate @pritidesai, I should have checked!
