### ISSUE TITLE
Action method requires "method:" to be specified

### ISSUE THREAD

**Issue by afrittoli** [apache/incubator-openwhisk-wskdeploy#961]
All the examples point to using something like this in the manifest:

```
    apis:
      my-api:
        /:
          /:
            my_action: GET
```

This doesn't work for me. I need to specify something like:

```
    apis:
      my-api:
        /:
          /:
            my_action:
              method: GET
```

Otherwise, I get the error: 

```
Error: manifest_parser.go [114]: [ERROR_YAML_PARSER_ERROR]: File: [manifest_todo_rest_api.yaml]: 
==> yaml: unmarshal errors:
==> line 12: cannot unmarshal !!str `GET` into map[string]parsers.APIMethodResponse
```

I'm using the latest available wskdeploy binary for mac.

```
$ wskdeploy version
wskdeploy version: latest
```

Upz, this might need fixing too.
I wonder if it's related to https://github.com/apache/incubator-openwhisk-wskdeploy/pull/951/files?

**Comment by mrutkows** [comment]
@afrittoli we had to go to a multi-line format and could not longer support the single-line format.  If you found this in our docs, please let us know where... I am sure some are out of date.

**Comment by pritidesai** [comment]
@brunogirin fixed the documentation in this PR:

https://github.com/apache/incubator-openwhisk-wskdeploy/commit/4aae2005b565300f08601cbb366b1b05f9a923a3
