### ISSUE TITLE
wskdeploy always append https to api url

### ISSUE THREAD

**Issue by itsmurugappan** [apache/incubator-openwhisk-wskdeploy#970]
my api url is http://hostname:port, when i run wskdeploy it always appends https like  https://http// . How to get around it ?

Warning: open /home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/runtimes/runtimes.json: no such file or directory
Error: Get https://http//hostname:port: dial tcp: lookup http on xx.xx.xx.xxx:XX: no such host

**Comment by pritidesai** [comment]
Sorry for delayed response, I have PR #983 checking if URL has "http://" or "https://" before appending https://
