### ISSUE TITLE
HTTP response documentation

### ISSUE THREAD

**Issue by brunogirin** [apache/incubator-openwhisk-wskdeploy#975]
The current documentation doesn't include any example that make use of HTTP responses. It would be good to add one that shows:
- what to change in the API definition
- what to change in the action itself and in particular:
    - how to return a success or an error structure using plain JSON
    - how to do the same using `Promise.resolve` and `Promise.reject`

**Comment by brunogirin** [comment]
@pritidesai can I close this issue now that you merged the PR?

**Comment by pritidesai** [comment]
thanks @brunogirin yes we can close this.
