### ISSUE TITLE
Dumps base64 (?) on failures

### ISSUE THREAD

**Issue by ScottChapman** [apache/incubator-openwhisk-wskdeploy#977]
I've been running into a problem for the past few days, I suspect it is due to a network timeout.

But what is happening is that I am running `wskdeploy` and it creates a few artifacts then appears to stop. It will eventually error out by flooding stdout with what appears to be base64 encoded data.

It might be a legit timeout issue, but it should behave better than that...

**Comment by pritidesai** [comment]
@ScottChapman please send me some sample so that I can take a look

**Comment by csantanapr** [comment]
Thanks @ScottChapman this error logs are helpful.
I see that the response includes the `code` artifact `"code":"UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAaW5`

@pritidesai if the code is a 48MB zip the response will include this, are you doing a GET on the action after deplployment to verify that it got deploy correctly?

You need to the query parameter `code=false` and only do `code=true` which is the default when no present when you actually trying to download the code artifact.

For example
```
https://openwhisk.ng.bluemix.net/api/v1/namespaces/_/actions/foo?code=false
```
I believe the client-go library was updated to always include `code=false`

**Comment by pritidesai** [comment]
Yeah the code is set to `true` explicitly which was needed for `export` functionality, let me change this behavior to only set it to `true` for `export` otherwise set it to `false`.
